### ISSUE TITLE
[CLOSED] 🌟 [EPIC] 1. Docker is running

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Wednesday Feb 17, 2021 at 18:14 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/1_

----

## 🌟 EPIC

- [x] Docker is running
- [x] Services work together
- [x] Tests are running on Github (e.g. Docker builds)
