### ISSUE TITLE
[CLOSED] 804 elopage registration

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1018]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Tuesday Oct 12, 2021 at 11:26 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/959_

----

## 🍰 Pullrequest

On the members area we have now a link to the registration on the Gradido Elopage when the User has not registered now,
else he gets a link to the sign_in page.

### Issues

- Fixes #804 
- Fixes #966 

### Todo

- [x] When User login gets a flag if his email is registered on the gdt server #949 
- [x] If yes button "Member Area" sends us to the Elopage Account 
- [x] if not button "..." has a visual queu (Red exclamation button) and sends us to the Elopage Registration "https://elopage.com/s/gradido/basic-de/payment?locale=de&prid=111&pid=&firstName=&lastName=&email="

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/959/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Mogge"><img src="https://avatars.githubusercontent.com/u/15882241?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mogge](https://github.com/Mogge)**
_Wednesday Oct 13, 2021 at 14:03 GMT_

----

I pushed with the backend coverage at 3%
