### ISSUE TITLE
[CLOSED] 🚀 [Feature] Change newsletter message when sign in and out.

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1098]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Sunday Oct 24, 2021 at 06:10 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/1039_

----

## 🚀 Feature
When you sign in and out of the newsletter the german success or information message shows a text that is to techy.  

## ToDos
- [ ] Change german text: "Du bist im Newslettersystem eingetraten." to "Du erhältst Informationen per E-Mail."
- [ ] Change german text: "Du bist aus Newslettersystem ausgetragen." to "Du erhältst keine Informationen per E-Mail."
- [ ] Change english text: "You are subscribed to newsletter system." to "You will receive information per e-mail."
- [ ] Change english text: "You are unsubscribed from newsletter system." to "You will not receive any information by e-mail."

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Sunday Nov 07, 2021 at 07:53 GMT_

----

@Elweyn Is this merged?
