### ISSUE TITLE
[CLOSED] feat: Setup Admin Interface

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1104]
<a href="https://github.com/Mogge"><img src="https://avatars.githubusercontent.com/u/15882241?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Mogge](https://github.com/Mogge)**
_Tuesday Oct 26, 2021 at 06:10 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1045_

----

## 🍰 Pullrequest
Setting up the admin interface

### Issues
- fixes #1034 

### Todo
- [X] Setup Docker and Docker Compose
- [X] NGINX (which port?, 8080?)
- [X] setup tests as in frontend
- [X] creare connection to graphql API
- [X] setup store
- [X] setup router
- [ ] Handle JWT (to be done when the backend can handle roles)
- [X] Setup i18n an locales
- [X] CI Workflow

----

_**[Mogge](https://github.com/Mogge)** included the following code: https://github.com/gradido/gradido/pull/1045/commits_
