### ISSUE TITLE
[CLOSED] [WIP] Apollo create user

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1112]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Wednesday Oct 27, 2021 at 13:15 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1053_

----

## 🍰 Pullrequest
Creation of community users in apollo exclusively

### Issues

- #835 

### Todo

- [ ] Create User on the login_server (Old call)
- [ ] Create DbUser and store it in the gradido_community database state_user table
- [ ] Send Email to user that demands to click the validation link

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/1053/commits_
