### ISSUE TITLE
[CLOSED] 🚀 [Feature] Build Admin Interface User Management

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1118]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Friday Oct 29, 2021 at 07:15 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/1059_

----

## 🚀 Feature
As supporter we need to find User, edit User Informations, send User activation email or send reset email.
Furthermore it would be great to see the coin creation of a User in his profil.

## ToDos:
- [x] Create User Management Page
- [x] Create User Search Component
- [x] Update User Component
- [x] Coin Created Component for User

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ogerly"><img src="https://avatars.githubusercontent.com/u/1324583?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ogerly](https://github.com/ogerly)**
_Wednesday Jan 19, 2022 at 08:58 GMT_

----

alles erledigt
