### ISSUE TITLE
[CLOSED] 🚀 [Feature] Build Admin Interface Coin Creation Management

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1119]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Friday Oct 29, 2021 at 07:37 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/1060_

----

## 🚀 Feature
As Supporter we need to create coins for multiple users, for this we have a page with every user or a filtered list.
In this list we need: 
- Select every User that gets a coin creation, 
- A user that has >= 1000 coins creation for the selected month needs to be fade out / not selectable
- Select one date for all creations, 
- Enter a message for all creations,
- Enter one amount for all creations,
- Each User gets a own message
- Each User gets a own amount
- Edit and Delete a coin creation

## ToDos:
- [x] Create Coin Creation Management Page
- [x] Use User Search Component / slots for specific user coin creation fields (Select, Message, Amount) \
- [x] Coin Creation Form Component / Date, Message, Amount for all creations \
- [x] Create a Coin Creation Transaction Page
- [x] Coin Creation Transaction Component / Edit & Delete \

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ogerly"><img src="https://avatars.githubusercontent.com/u/1324583?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ogerly](https://github.com/ogerly)**
_Thursday Nov 25, 2021 at 10:03 GMT_

----

work an this https://github.com/gradido/gradido/issues/1124
