### ISSUE TITLE
[CLOSED] 🚀 [Feature] Build Admin Interface Coin Creation Transaction List

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1120]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Friday Oct 29, 2021 at 07:52 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/1061_

----

## 🚀 Feature
As supporter we need to have a list of coin creations with their informations, so that we can edit or delete some.

## ToDo
- [x] Create Transaction List Page
- [x] Create Transaction Search Component
- [x] Edit and Delete functionality

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Saturday Oct 30, 2021 at 18:16 GMT_

----

I think we should not allow to edit or delete transactions. This violates perceived banking "standards".

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ogerly"><img src="https://avatars.githubusercontent.com/u/1324583?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ogerly](https://github.com/ogerly)**
_Tuesday Nov 02, 2021 at 05:35 GMT_

----

> I think we should not allow to edit or delete transactions. This violates perceived banking "standards".

du you mean actual transaction or gdd creation  ?

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Sunday Nov 07, 2021 at 13:42 GMT_

----

Once a gdd transaction is visible on an account it should never be taken back. There can be additional transactions to correct a faulty state, but once booked things should never be changed. This does not mean we can create Transactions in two steps - create the transaction and then confirm it to make it permanent and irreversible.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Tuesday Dec 14, 2021 at 06:36 GMT_

----

I think that this is done. What do you think? @ogerly @ulfgebhardt?
We get a list of not confirmed pending creations.

Or was this to get a list of all confirmed creations?

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ogerly"><img src="https://avatars.githubusercontent.com/u/1324583?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ogerly](https://github.com/ogerly)**
_Tuesday Dec 14, 2021 at 12:36 GMT_

----

this task is completed. i am completing this task.
