### ISSUE TITLE
[CLOSED] login_call_create_user

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1129]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Sunday Oct 31, 2021 at 04:12 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1070_

----

## 🍰 Pullrequest

This implements `createUser` of the `login_server` on Apollo.

### Issues

- requires #1037 
- fixes #835 

### Todo

- [x] pub/priv key generation
- [x] send email
- [x] (optional) login
- [x] test
- [x] figure wordlists

----

_**[ulfgebhardt](https://github.com/ulfgebhardt)** included the following code: https://github.com/gradido/gradido/pull/1070/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Sunday Oct 31, 2021 at 05:00 GMT_

----

@Elweyn I think your solution for this in https://github.com/gradido/gradido/pull/1053 is not sufficient. Please have a look.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Sunday Oct 31, 2021 at 11:17 GMT_

----

I know I just started it and had to make some changes on bug tickets, could not continue on it!
Did you make it work on your local machin?

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Sunday Oct 31, 2021 at 17:43 GMT_

----

I did not even try to run this on my local machine, since its misisng the `pubKey` part. The `pubKey` is required for our session to identify the user (jwt). We should make sure we can generate it to ensure backward compatibility.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Wednesday Nov 03, 2021 at 20:34 GMT_

----

My test results after i fixed the  private key encryption:

```
mutation{createUser(email: "peter@lustig.de", firstName: "peter", lastName: "lustig", password: "123!AAAb", language: "petersprech")}
```

```
INSERT INTO `login_users` (`id`, `email`, `first_name`, `last_name`, `username`, `description`, `password`, `pubkey`, `privkey`, `email_hash`, `created`, `email_checked`, `passphrase_shown`, `language`, `disabled`, `group_id`, `publisher_id`) VALUES
// old - generated via login server
(1, 'peter@lustig.de', 'peter', 'lustig', '', '', 4747956395458240931, 0x8c75edd507f470e5378f927489374694d68f3d155523f1c4402c36affd35a7ed, 0xb0e310655726b088631ccfd31ad6470ee50115c161dde8559572fa90657270ff13dc1200b2d3ea90dfbe92f3a4475ee4d9cee4989e39736a0870c33284bc73a8ae690e6da89f241a121eb3b500c22885, 0x9f700e6f6ec351a140b674c0edd4479509697b023bd8bee8826915ef6c2af036, '2021-11-03 20:05:04', 0, 0, 'de', 0, 1, 0);
// new - generated via community server
(2, 'peter@lustig.de', 'peter', 'lustig', '', '', 4747956395458240931, 0x8c75edd507f470e5378f927489374694d68f3d155523f1c4402c36affd35a7ed, 0xb0e310655726b088631ccfd31ad6470ee50115c161dde8559572fa90657270ff13dc1200b2d3ea90dfbe92f3a4475ee4d9cee4989e39736a0870c33284bc73a8ae690e6da89f241a121eb3b500c22885, 0x9f700e6f6ec351a140b674c0edd4479509697b023bd8bee8826915ef6c2af036, '2021-11-03 20:22:15', 0, 0, 'de', 0, 1, 0);
```
```
INSERT INTO `login_user_backups` (`id`, `user_id`, `passphrase`, `mnemonic_type`) VALUES
// old - generated  via login server
(1, 1, 'behind salmon fluid orphan frost elder amateur always panel palm leopard essay punch title fun annual page hundred journey select figure tunnel casual bar ', 2);
// new - generated via community server
(2, 2, 'behind salmon fluid orphan frost elder amateur always panel palm leopard essay punch title fun annual page hundred journey select figure tunnel casual bar ', 2);
```

TODOs:
- [x] Send activation email
- [x] SQL Transaction
- [x] Config Fields

Considering the test of @einhornimmond we can assume that the private key has no relevance for the current software, since it was not yet encrypted and therefore should not have worked with existing software.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/einhornimmond"><img src="https://avatars.githubusercontent.com/u/67117805?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [einhornimmond](https://github.com/einhornimmond)**
_Wednesday Nov 03, 2021 at 20:56 GMT_

----

> Considering the test of @einhornimmond we can assume that the private key has no relevance for the current software, since it was not yet encrypted and therefore should not have worked with existing software.

Hm okay, das ist merkwürdig. Ich habe nachdem Anlegen des Benutzers über view in die Datenbank geschaut und der Eintrag für den public-key und den private-key sahen korrekt aus. Sie hatten beide die gleiche Länge wie die Einträge meiner bisherigen Benutzer. Der private Key hatte die Länge von 80 Bytes also ein verschlüsselter 64 Byte Key. 
Ich habe nochmal in dein Code geschaut und du hast recht, in der Version die ich habe, wurde der private key noch nicht verschlüsselt gespeichert. Aber der Password Hash und die Passphrase. 
Das heißt dann wohl das an der Stelle mein Login-Server den fehlerhaft gespeicherten Private Key aus der gespeicherten Passphrase erstellt hat und dann korrekt abgespeichert hat. Da es keine Fehlermeldung gab waren sowohl der Passwort Hash als auch der public key korrekt. Solange die Passphrase noch unverschlüsselt gespeichert wird geht das noch so einfach.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Thursday Nov 04, 2021 at 13:39 GMT_

----

Open TODOs:
- [ ] Send Email with registrationLink
- [x] Send error Email in case of error

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Thursday Nov 04, 2021 at 17:05 GMT_

----

I suggest to not send emails in error cases. We should handle this in a more general form like an error listener or alike.
What you think @Elweyn ?

Also:
- [x] Generate correct verification code (needed?)

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Thursday Nov 04, 2021 at 17:09 GMT_

----

@Elweyn Can you take a look at the comment on this and have an opinion pls: https://github.com/gradido/gradido/pull/1070/commits/867ffee7b7e8420f9bca538b60a1460b3d6277c7

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Mogge"><img src="https://avatars.githubusercontent.com/u/15882241?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mogge](https://github.com/Mogge)**
_Thursday Nov 04, 2021 at 19:11 GMT_

----

Just reduce the coverage of the backend to get it merged. I suggest to have a separate PR for sending emails.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Thursday Nov 04, 2021 at 22:01 GMT_

----

> Just reduce the coverage of the backend to get it merged. I suggest to have a separate PR for sending emails.

I'd suggest to merge `createTransaction` first, which contains the email code library, and implement it after another rebase on here. We would break an essential functionality if we merge this without emails.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Saturday Nov 06, 2021 at 01:01 GMT_

----

@Mogge Thank you for the review - I also included the email for account activation now. Please have another quick look so I can be confident everything is still fine. Please also check if the conversation can be resolved from your point of view. ❤️
