### ISSUE TITLE
[CLOSED] Login call unsecure login

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1154]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Wednesday Nov 10, 2021 at 04:50 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1095_

----

## 🍰 Pullrequest
When a login call is triggered on the apollo server, this one calls the unsecureLogin method in the login_server.
This PR should refactor the logic so we have everything in the apollo server.

### Issues
- fixes #832 

### Todo
- [x] Store email
- [x] Store password
- [x] Store username
- [x] Load user from DB
- [x] Check password validity
- [x] Check hasElopage
- [x] If user exists and don't have pubKey => Generate it again & update the user

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/1095/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Wednesday Nov 10, 2021 at 17:33 GMT_

----

@Elweyn The newest master contains the hasElopage call

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Wednesday Nov 17, 2021 at 18:43 GMT_

----

I committed a change regarding my suggestion for the pubKey in the token. I reduced code changes that way I believe. But make sure to have another look there and figure out if thats cool how it is @Elweyn
