### ISSUE TITLE
[CLOSED] Adding a check that the user is activated before letting them login.

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1158]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Friday Nov 12, 2021 at 06:19 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1099_

----

## 🍰 Pullrequest
bugfix on the master branch tag 1.5.1 we have a problem with the registration that makes that the user is not registrated on KlickTipp. Fix: Change the process so that the user needs to validate his email before he can login.

### Issues
- Fixes: #1088 

### TODOs

- [X] Check if user is activated
- [x] Change the register.vue so that we say to the user that he needs to validate his email.
- [x] Change the error message for not activated user?
- [ ] Login when not Activated > Redirect to "Hey you did not confirm your EMail yet - want a new Email?"-Page, not logged in
- [ ] Click on Link in Email -> "Hey nice, lets go and login"

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/1099/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Friday Nov 12, 2021 at 06:58 GMT_

----

@einhornimmond, @ulfgebhardt, @ogerly,
could you guys please review this it would be great!!!! 😄

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Friday Nov 12, 2021 at 08:16 GMT_

----

## TODOs
- [ ] Login when not Activated > Redirect to "Hey you did not confirm your EMail yet - want a new Email?"-Page, not logged in
- [ ] Click on Link in Email -> "Hey nice, lets go and login"

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/einhornimmond"><img src="https://avatars.githubusercontent.com/u/67117805?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [einhornimmond](https://github.com/einhornimmond)**
_Friday Nov 12, 2021 at 12:33 GMT_

----

What just occurred to me, because you changed the login-server code I must merge my other hotfixes into this branch. 
Luckly I have build the hotfixes on the 1.5 version and not on the master.
