### ISSUE TITLE
[CLOSED] Login hook elopage

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1171]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Wednesday Nov 17, 2021 at 16:00 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1112_

----

### Issues

- fixes #1093 
- fixes #1108 

### Todo

- [ ] test
- [x] clarify how the user sets his password when creating an user via elopage hook @einhornimmond 
- [x] clarify how the database field `elopage_user_id` is filled - how is the production data on this? @einhornimmond 
- [x] clarify if there is webhooks on the community server doing similar things? @einhornimmond 
- [x] one field is multiplied with `100.0f` - I assume its the amount donated. Why is it multiplied? Or is it a different field? @einhornimmond 

----

_**[ulfgebhardt](https://github.com/ulfgebhardt)** included the following code: https://github.com/gradido/gradido/pull/1112/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/einhornimmond"><img src="https://avatars.githubusercontent.com/u/67117805?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [einhornimmond](https://github.com/einhornimmond)**
_Thursday Nov 18, 2021 at 12:48 GMT_

----

`clarify how the user sets his password when creating an user via elopage hook `
Via Email Verification Code. 
User get's email, click on link and checkEmail will automatic forward user to update password page if no password was set. 
After the User has choosen a password, his key pair will be generated and saved encrypt with his password and email and the passphrase should be saved encrypted with a server admin public key, but at the moment it is saved unencrypted. 
In the Past that was also the place to show the User his Passphrase so he can store it away save. But it leads to much confusion. So we have disabled this feature. 

`clarify how the database field elopage_user_id is filled - how is the production data on this?`
It isn't filled at all. 
On production there all filled with 0.
By designing the table I thought the publisher_id is the elopage_user_id so I would fill them later. But I never finished it.

`clarify if there is webhooks on the community server doing similar things?`
No, the community server don't listen at the elopage webhooks. 

`one field is multiplied with 100.0f - I assume its the amount donated. Why is it multiplied? Or is it a different field?`
I save the product_price as int so I need to multiple the decimal value I get from elopage to get euro cent. 
It is for preventing accuracy loss which sometimes happen with specific numbers saved in decimal format.
