### ISSUE TITLE
[CLOSED] backend_rights

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1185]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Saturday Nov 20, 2021 at 18:37 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1126_

----

## 🍰 Pullrequest

Implements a roles & rights based system for authentication & authorization.

### Issues

- based on #1125 

### Todo

- [x] Admin role check (requires #1121 )
- [x] Clarify if we want to encode role in jwt to save a constant database query @Mogge 
- [x] test
- [x] set `isAdmin` based on role

----

_**[ulfgebhardt](https://github.com/ulfgebhardt)** included the following code: https://github.com/gradido/gradido/pull/1126/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Thursday Nov 25, 2021 at 08:59 GMT_

----

@Mogge Please have a look at this - especially the `isAuthorized` - we make a database query on every call to the server to figure out the role - alternatively we can save the role identifier or whatever in JWT and prevent an additional query.

I have implemented this to your requirements with a database query - the JWT just contains the User-Identifier (currently the pubKey)
