### ISSUE TITLE
[CLOSED] [WIP] Login call reset password frontend

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1192]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Tuesday Nov 23, 2021 at 08:41 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1133_

----

## 🍰 Pullrequest
The frontend needs to be changed so that we set the password after the registration has been done & the acount is activated.

### Issues

- relates #1130  

### Todo

- [ ] Register form withdraw password fields
- [ ] Refactor ResetPassword so that it works for /reset & /checkEmail
- [ ] Send them to thx/reset or thx/checkEmail

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/1133/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Wednesday Nov 24, 2021 at 03:33 GMT_

----

@Elweyn Damn I haven't seen this in time - i made a basic implementation of the frontend to test the backend - so no text changes or any fancy hint texts like you did - we should try to combine both PRs as soon as possible in order to not make the work twice.
See: #1130

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Friday Nov 26, 2021 at 01:51 GMT_

----

closing this since its now part of #1130
@Elweyn
