### ISSUE TITLE
[CLOSED] proto_signatures

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1193]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Wednesday Nov 24, 2021 at 10:20 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1134_

----

## 🍰 Pullrequest

Implements the protobuff signatures:
- transactions.tx_hash
- transaction_signatures
- login_pending_tasks

This is done to replicate the old database in its entity with all data present before. We decided to do this as experiment since the `login_pending_tasks` does not hold the data in unencrypted form - just as protobuff data.

### Issues

- None

#### login_admin_pending_tasks
peter@lustig.de schöpft 1000 für Dezember für bob@baumeister.de no memo

before:
```
insert into login_pending_tasks(id,user_id,request,created,finished,result_json,param_json,task_type_id,child_pending_task_id,parent_pending_task_id) values('2','4','
f
d
 r���2X����s�1�Q�w�\�8,c��xN�p@�F��+s�]���µA�
C�����Ȉn�V�͜�^-o�"�k'ʇ�|�sg��Q�P`;��ύ:1
'
 �	١F7O�u�g}���J���ީm�@S�m��~���	����','2021-12-10 23:27:14','2000-01-01 00:00:00','','{"blockchain_type":1}','10','0','0');
```

after:
```
insert into 
login_pending_tasks(id,user_id,request,created,finished,result_json,param_json,task_type_id,child_pending_task_id,parent_pending_task_id) values('4','4','
f
d
 r���2X����s�1�Q�w�\�8,c��xN�p@�!g���F]���ֵoUY���
|_��f�]n��/O�9����՚�"�4�+X�K�
�*Wu��=
��ύ:1
'
 �	١F7O�u�g}���J���ީm�@S�m��~���	��ύ','2021-12-10 23:27:14','2000-01-01 00:00:00','','{"blockchain_type":1}','10','0','0');
```

The difference can be explained by the timestamp seconds when the block was created which is encoded into to protobuff. Remaining date values are the same. The signature resulting from the block will obviously differ and is also included.

I consider this close enough.

### Todo

- [x] login_pending_tasks
- [x] refactor
- [x] decay start block
- [ ] verify that `transactions.txHash` has the correct values
- [ ] verify that `transaction_signatures` has the same entries
- [x] verify that `login_admin_pending_tasks` has the same entries

----

_**[ulfgebhardt](https://github.com/ulfgebhardt)** included the following code: https://github.com/gradido/gradido/pull/1134/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Monday Dec 06, 2021 at 23:41 GMT_

----

> This is a hell of a PR

In a good or bad way? xD

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Friday Jan 28, 2022 at 00:12 GMT_

----

Closing this - not needed
