### ISSUE TITLE
[CLOSED] Admin pending creation

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1194]
<a href="https://github.com/ogerly"><img src="https://avatars.githubusercontent.com/u/1324583?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ogerly](https://github.com/ogerly)**
_Wednesday Nov 24, 2021 at 10:46 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1135_

----

## 🍰 Pullrequest
backend: creations pending

### Issues
- relates #1116 

Open Questeion: 
Creation amount is higher than current month allowed. how do we deal with this? do we subtract an amount from a present month or do we change the amount to be created to the lower open creation amount?

### TODOs:
- [x] Prepare apollo call
- [x] Implement call in frontend
- [x] Update frontend
- [ ] Moderator is used with static data: @ulfgebhardt said to look at ``verifyLogin``
- [x] Change ``note`` to ``memo``
- Refactor getUserCreations => https://github.com/gradido/gradido/issues/1145

----

_**[ogerly](https://github.com/ogerly)** included the following code: https://github.com/gradido/gradido/pull/1135/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Mogge"><img src="https://avatars.githubusercontent.com/u/15882241?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mogge](https://github.com/Mogge)**
_Wednesday Dec 01, 2021 at 11:51 GMT_

----

@ogerly , @Elweyn What about the last to do here? I would like to merge this PR

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Thursday Dec 02, 2021 at 04:59 GMT_

----

@Mogge I have the last review on the list! I would do this now and hope we can merge it after!
