### ISSUE TITLE
[CLOSED] WIP: Change the getUserCreations function.

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1222]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Wednesday Dec 08, 2021 at 11:42 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1163_

----

## 🍰 Pullrequest
getUserCreations makes 6 Calls to the database so we want to change the calls so we only need 1 or maximal 2 calls for the transaction_creations and login_pending_tasks_admin

### Issues

- fixes #1145

### Todo

- [ ] Create call on transaction_creations
- [ ] Create call on login_pending_tasks_admin
- [ ] Calculate the open creations
- [ ] Test functionality

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/1163/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Wednesday Dec 08, 2021 at 11:51 GMT_

----

Wrong start branch
