### ISSUE TITLE
[CLOSED] 1145 refactor admin resolver from master

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1223]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Wednesday Dec 08, 2021 at 11:51 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1164_

----

## 🍰 Pullrequest
getUserCreations makes 6 Calls to the database so we want to change the calls so we only need 1 or maximal 2 calls for the transaction_creations and login_pending_tasks_admin

### Issues

- fixes #1145
- fixes #1165 

### Todo

- [x] Create call on transaction_creations
- [x] Create call on login_pending_tasks_admin
- [x] Calculate the open creations
- [x] Test functionality

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/1164/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Wednesday Dec 15, 2021 at 23:24 GMT_

----

This looks great - thank you for optimizing those queries!
