### ISSUE TITLE
[CLOSED] Moved reverse of the getPendingCreations to the AdminResolver instead…

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1244]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Monday Dec 13, 2021 at 11:36 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1185_

----

… to do it in the CreationConfirm page.

### Issues

- #1165 

### Todo

- [X] Remove 10000 of Frontend & Admin
- [X] Move array.reverse to backend
- [x] Use floats instead of integer 
- [x] Remove GraphQL error

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/1185/commits_
