### ISSUE TITLE
[CLOSED] Refactoring of the sendActivationEmail so that we can send another em…

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1257]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Friday Dec 17, 2021 at 09:16 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1198_

----

…ail with a new activation link.

### Issues

- fixes #1196  

### Todo

Backend
- [X] Create a mutation to resendActivationEmail
```
mutation {
  sendActivationEmail(email:"peter@lustig.de")
}
```

Frontend
- [ ] Implement button on /Thx/login that sends the resendActionEmail mutation to apollo. (Maybe we need to change the page on which we do this.)

Admin
- [ ] Add resend button to UserTable or its entries that sends the resendActionEmail mutation to apollo

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/1198/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Monday Dec 20, 2021 at 10:23 GMT_

----

Has been merge #1202
