### ISSUE TITLE
[CLOSED] 🔧 [Refactor] admin interface refactor

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1268]
<a href="https://github.com/ogerly"><img src="https://avatars.githubusercontent.com/u/1324583?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ogerly](https://github.com/ogerly)**
_Tuesday Dec 21, 2021 at 14:26 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/1209_

----

Folgende arbeiten sollten noch im Admin interface erledigt werden. 
## 🔧 Refactor ticket
-  [x] Admin interface updated sich nicht automatisch in der user liste bei schöpfung ( #1197 )
-  [x] Schöpfungs bestätigung nochmal die Daten auflisten ( #1197 )
-  [x] der button "Alle nicht bestätigte EMail" neben input suche suche (#1214 )
-  [x] Monatskürzel in der Tabelle (in fields keys)  (#1214 )
-  [x] Vordefinierten Text für die Schöpfung (#1214 )
-  [ ] Selbstschöpfung ausschalten (#1214 )
-  [x] Sprache Übersetzung (#1218 )
-  [ ] Wie lange ist der Link gültig (email bestätigen)
