### ISSUE TITLE
[CLOSED] new_deployment

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1279]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Thursday Dec 30, 2021 at 04:09 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1220_

----

## 🍰 Pullrequest

This describes how to prepare a bare debian server to run gradido and will also provide a install script which can be executed once the minimum requirements are met. This is for a docker-less setup on a bare-metal-server.

### Issues

- fixes #1171 

### Todo

- [X] Setup Description
- [x] Install script
- [x] nginx configs
- [x] align with docker nginx configs
- [x] pm2 configs
- [ ] ~~stop command~~
- [ ] ~~restart command~~
- [x] start (branch) command
- [x] github webhook endpoint
- [x] add another ssh key (@clauspeterhuebner ) 
- [x] email setup
- [ ] switch branch from new_deployment to master after merge

Followup:
- #1286

----

_**[ulfgebhardt](https://github.com/ulfgebhardt)** included the following code: https://github.com/gradido/gradido/pull/1220/commits_
