### ISSUE TITLE
🌟 [EPIC] Testing & Seeding

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1298]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Thursday Jan 06, 2022 at 08:12 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/1239_

----

## 🌟 EPIC

Testing & Seeding

## 🤖 Tests
- Authentifizierung: 
- [ ] Registrierung
- [ ] Passwort setzen
- [ ] Passwort zurücksetzen
- [ ] Anmelden
- [ ] Nutzer gibt falsches Passwort ein => Erwartung Fehler wird geschmissen
- Schöpfen
- [ ] Schöpfung einreichen
- [ ] Dialog zu Schöpfung Admin > User
- [ ] Dialog zu Schöpfung User > Admin 
- [ ] Schöpfung akzeptieren
- [ ] Schon akzeptierte Schöpfung erneut akzeptieren => Erwartung Fehler wird geschmissen
- [ ] Schon akzeptierte Schöpfung erneut löschen => Erwartung Fehler wird geschmissen
- [ ] Schöpfung ablehnen
- [ ] Schon abgelehnte Schöpfung erneut ablehnen => Erwartung Fehler wird geschmissen
- [ ] Schon abgelehnte Schöpfung erneut akzeptieren => Erwartung Fehler wird geschmissen
- GDD senden
- [ ] Senden an existierende Email
- [ ] Senden an nicht vorhandene Email => Erwartung Fehler wird geschmissen
- [ ] Gleichzeitiges senden von Transaktionen (Mathias > Hannes, Alex > Hannes, Hannes > Alex)
- GDD per link senden
- [ ] Link erstellen
- [ ] Ich löse den Link selber ein => Erwartung Fehler wird geschmissen
- [ ] Andere Person löst den Link ein
- [ ] Link an mehrere Personen geben (Erwartet nur einer kann den Link einlösen)
- [ ] Abgelaufener Link einlösen => Erwartung Fehler wird geschmissen
- [ ] Gelöschter Link einlösen => Erwartung Fehler wird geschmissen
- Transaktionen
- [ ] Liste aller Transaktionen sichtbar & Pagination
- GDT Konto
- [ ] Liste aller GDT Einträge sichtbar & Pagination
- Einstellungen
- [ ] Sprache wechseln
- [ ] Passwort wechseln
- [ ] GdtAmount sichtbar / unsichtbar
- [ ] GddAmount sichtbar / unsichtbar
- Contribution Link
- [ ] Erstellen ein contribution link
- [ ] Contribution link abrufen
- [ ] Contribution link am gleichen Tag nochmal einlösen => Erwartung Fehler wird geschmissen
- [ ] Zweite Person ruft contribution Link auf
- [ ] Abgelaufener contribution link abrufen => Erwartung Fehler wird geschmissen
