### ISSUE TITLE
[CLOSED] 🔧 [Refactor] ADMINAREA - creation transactionlist revise

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1428]
<a href="https://github.com/ogerly"><img src="https://avatars.githubusercontent.com/u/1324583?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ogerly](https://github.com/ogerly)**
_Saturday Jan 29, 2022 at 07:39 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/1369_

----

## 🔧 Refactor ticket

the field decay will be removed and there will be two new fields. 
1. the moderator who created the field
2. the date for which period the creation was made.

![unknown](https://user-images.githubusercontent.com/1324583/151652257-3ca49811-3e3e-4c04-abb9-464ca347c2c5.png)

## TODOs
- [x] Remove column 'Vergänglichkeit' (Decay)
- [x] Add actuel creation date to the Transaction Table (Not the date where the creation were done)
- [x] Add Moderator Id to the Transaction Table
- [x] Query the two new columns in the transaction creation list (UserSearch)
