### ISSUE TITLE
[CLOSED] Refactor - Remove community_server

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1467]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Wednesday Feb 02, 2022 at 14:05 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1408_

----

## 🍰 Pullrequest
Remove the community_server folder and each references in the gradido folder.

### Issues

- requires #1407

### Todo

- [X] Create new Repository community_server
- [X] Move directory community_server in gradido/gradido to gradido/community_server
- [x] Set tag last-community_server on master

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/1408/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Thursday Feb 03, 2022 at 05:03 GMT_

----

@Mogge OK so I would make a git tag -a last-community_server & instead of deleting community_server folder create a new Repository did I understand it right?

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Thursday Feb 03, 2022 at 06:04 GMT_

----

Created a repository community_server on the gradido organization!
