### ISSUE TITLE
[CLOSED] Refactor: Combine transaction tables

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1582]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Sunday Feb 20, 2022 at 03:23 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1523_

----

## 🍰 Pullrequest

This PR combines the transaction tables `transactions`, `transaction_creations` and `transaction_send_coins` into `transactions`. It also simplifies the transaction logic & seed.

Further improvements:
- Removed several repositories
- Fixed Bug with Names of sender/recipient not showing due to deleted account
- Corrected lots of database fields not properly defined
- Type-safety on seed users
- fixed [bug](https://github.com/gradido/gradido/commit/babe2b4930403b04d7f4c5710fe1a7a704ef779e) in frontend of unknown origin

### Issues

- None

### Todo

- [ ] Whats up with the frontend time format? [commit](https://github.com/gradido/gradido/commit/babe2b4930403b04d7f4c5710fe1a7a704ef779e) + [reference](https://tc39.es/proposal-intl-DateTimeFormat-formatRange/)
- [x] does the seed work? (pairing if needed)
- [x] Please test this with seed data

----

_**[ulfgebhardt](https://github.com/ulfgebhardt)** included the following code: https://github.com/gradido/gradido/pull/1523/commits_
