### ISSUE TITLE
[CLOSED] v1.6.6

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1600]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Friday Feb 25, 2022 at 16:01 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1541_

----

## 🍰 Pullrequest

New release candidate 1.6.6

### Issues

- None

### Todo

- [ ] Merge & Test
- [ ] Specifically check for delete user functionality
- [ ] Specifically check for correct transaction & balance values
- [ ] Specifically check if transaction still work properly

----

_**[ulfgebhardt](https://github.com/ulfgebhardt)** included the following code: https://github.com/gradido/gradido/pull/1541/commits_
