### ISSUE TITLE
[CLOSED] Query-transaction-link

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1645]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Wednesday Mar 09, 2022 at 14:26 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1586_

----

## 🍰 Pullrequest
The frontend needs a query where it can get the TransactionLink information for a given code.

### Issues
- fixes #1557 
- require #1585 

### Todo
- [X] Query transactionLink for a given code 
- [X] Get User information from the transactionLink.userId
- [X] Return TransactionLink with every information

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/1586/commits_
