### ISSUE TITLE
[CLOSED] Frontend: show link information

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1654]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Wednesday Mar 09, 2022 at 17:10 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1595_

----

## 🍰 Pullrequest

We need a page to show the informations of the transaction link. 
Shows the firstName, lastName and the amount of a specific transaction link.

### Issues

- fixes #1558 

### Todo

- [X] Create a page to show the transactionLink
- [X] Call backend query transactionLinkInformation 
- [X] Link new page to /redeem/:code
- [x] Show transaction Link Informations on the page
- [ ] Add button to redeem the transactionLink to my own account
- [ ] Add button to register if no user is authenticated now

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/1595/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Mogge"><img src="https://avatars.githubusercontent.com/u/15882241?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mogge](https://github.com/Mogge)**
_Thursday Mar 10, 2022 at 14:44 GMT_

----

Can we have a better title for this PR, please?

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Mogge"><img src="https://avatars.githubusercontent.com/u/15882241?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mogge](https://github.com/Mogge)**
_Saturday Mar 19, 2022 at 12:10 GMT_

----

Can we close the PR @ogerly ?

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Monday Mar 21, 2022 at 08:04 GMT_

----

Integrated in #1620
