### ISSUE TITLE
[CLOSED] Feature: Eslint i18n validation

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1677]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Tuesday Mar 15, 2022 at 03:24 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1618_

----

## 🍰 Pullrequest

Validate our language files with eslint:
- find missing keys
- find unused keys
- no more stray text in the application
- more rules for i18n

### Issues

- fixes #1614
- fixes #374
- fixes #1573

### Todo

- [x] Confirm all required keys are there (visual inspection was good)
- [x] Remove `i18n:report` and corresponding plugins if possible
- [x] Admin
- [x] check the dynamic keys again
- [x] fix tests

----

_**[ulfgebhardt](https://github.com/ulfgebhardt)** included the following code: https://github.com/gradido/gradido/pull/1618/commits_
