### ISSUE TITLE
[CLOSED] Feature: Enforce config versions

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1686]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Friday Mar 18, 2022 at 02:23 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1627_

----

## 🍰 Pullrequest

Enforces a config version on backend and database to ensure the config on those are updated before the service can start.

### Issues

- fixes #1486

### Todo

- [x] Figure out how to do that in the frontends
- [x] fix frontend - meta from config
- [x] fix frontend - remove deprecated
- [x] admin

----

_**[ulfgebhardt](https://github.com/ulfgebhardt)** included the following code: https://github.com/gradido/gradido/pull/1627/commits_
