### ISSUE TITLE
[CLOSED] 🍰 Add Wallet Link To Mails

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1824]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Tuesday Apr 12, 2022 at 10:21 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1765_

----

### Issues

- fixes #1734 

### Todo

- [x] should other e-mails containing this link as well? or other links?
  - no
- [x] set correct client URI
- [x] implement `EMAIL_CLIENT_URI` config
  - [x] therefore increment `CONFIG_VERSION` by searching for `v4.2022-04-05`
- [x] test e-mail text and link manually
- [x] write tests
- [x] clean up: search for `Wolle`

----

_**[Tirokk](https://github.com/Tirokk)** included the following code: https://github.com/gradido/gradido/pull/1765/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Mogge"><img src="https://avatars.githubusercontent.com/u/15882241?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mogge](https://github.com/Mogge)**
_Wednesday Apr 13, 2022 at 14:52 GMT_

----

What do you think about this package?
https://github.com/forwardemail/email-templates

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Thursday Apr 14, 2022 at 07:11 GMT_

----

> https://github.com/forwardemail/email-templates

We can investigate this for the future. I can make an issue for it? @Mogge 
👍🏼

But in this issue just adding a link is the task I do understand.

PS: I added the pakage as recommendation to #1288 .

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Thursday Apr 14, 2022 at 12:32 GMT_

----

!!! solved

If I pull the actual master without conflicts then the frontend tests are not running anymore @ogerly

This happens as well when I pull the actual master in a clean branch. 🤔

It looks like the cause is the merged QR-Code.
