### ISSUE TITLE
[CLOSED] 🍰 Refactor notActivated and isDeleted

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1850]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Tuesday Apr 19, 2022 at 12:45 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1791_

----

### Issues

- fixes #1685

### Todo

- [x] cleanup: search for `Wolle`
- [x] rename `notActivated` to `filterByActivated`
- [x] rename `isDeleted` to `filterByDeleted`
- [x] rename `filterCheckedEmails` to `filterByActivated` etc.
- [x] rename `filterDeletedUser` to `filterByDeleted` etc.
- [x] created a follow up issue for `create filter object`: #1840

----

_**[Tirokk](https://github.com/Tirokk)** included the following code: https://github.com/gradido/gradido/pull/1791/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Thursday Apr 21, 2022 at 06:18 GMT_

----

I have researched again an found that with `notActivated` only users with unchecked e-mails are listed.
But then the name `withActivated` is not approbriate.

It should be named `onlyInactivated`. @ulfgebhardt @Mogge 
But then have have to leave the logic negated. I understand now why @Elweyn has done it negated.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Thursday Apr 21, 2022 at 10:04 GMT_

----

I could not find a quick solution to create a seperate filter object.
For me this seems to be to much research how to rewrite the code in detail.
