### ISSUE TITLE
[CLOSED] [WIP] Unused – 🍰 Refactor THX Page – First Aproach With Backend Enum Errorhandling

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1869]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Wednesday Apr 20, 2022 at 13:02 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1810_

----

## 🍰 Pullrequest

Refactor THX page.

### Issues

- fixes #1697

### Todo

- search for:
  - [ ] `forgot-password`
  - [ ] `checkEmail`
  - [ ] `reset-password`
  - [ ] `thx`
  - [ ] and think if changes are neccessary in links
- [ ] is `ResetPassword.vue` used and not only redirected by the router?
- [ ] shall `UserPassword.vue` should get a page thx massage as well?
- [ ] change position of languages snippets in language files?
  - [ ] especially for `site.thx.XXX`
  - [ ] remove? `site.login.signin`
- [ ] clean up: search for `Wolle`

----

_**[Tirokk](https://github.com/Tirokk)** included the following code: https://github.com/gradido/gradido/pull/1810/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Thursday Apr 28, 2022 at 09:03 GMT_

----

## !!! is soled now by @ogerly 

I get this error on `yarn lint --fix` even though `error` is excluded in locales in Eslint config.

<img width="722" alt="Bildschirmfoto 2022-04-28 um 10 11 37" src="https://user-images.githubusercontent.com/25344101/165717422-978db823-234d-465c-b284-8026052b81d5.png">

How can this error be ignored? @ogerly @mogge @ulfgebhardt @Elweyn
