### ISSUE TITLE
[CLOSED] [WIP][SubPR] 🍰 Implement Enum Backend Errors – A Draft To Discuss

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1916]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Friday Apr 29, 2022 at 09:05 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1857_

----

## 🍰 Pullrequest

As sub PR to #1858 
!!! May we have to change the parent PR number and the compared branch if there come more sub branches inbetween !!!

Implement enum backend errors – a draft to discuss.

### Issues

- fixes #1850

### Todo

- [x] have subs in your eyes
- [ ] is locale identifiers:
  - [ ] `settings.password.reset` still needed?
  - [ ] why `user-already-exists` is still in the master?
  - [ ] `message.activateEmail` seems unused
  - [ ] `message.unsetPassword` seems unused

----

_**[Tirokk](https://github.com/Tirokk)** included the following code: https://github.com/gradido/gradido/pull/1857/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Wednesday Aug 24, 2022 at 07:14 GMT_

----

We close this one in favor of #2141
