### ISSUE TITLE
[CLOSED] refactor: 🍰 Refactor THX Page – 2. Step

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1917]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Friday Apr 29, 2022 at 09:43 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1858_

----

## 🍰 Pullrequest

Refactor THX page – 2. step.

Replaces PR #1810 with less commits and without backend enum error handling.

Has sub PR #1857 .

### Issues

- fixes #1697
- fixes #1810 

### Todo

- search for:
  - [x] `forgot-password`
  - [x] `checkEmail`
  - [x] `reset-password`
  - [x] `thx`
  - [x] and think about if changes are neccessary in links
- [x] change position of languages snippets in language files?
  - [x] especially for `site.thx.XXX`
  - [x] remove `site.login.signin`?
- [x] refactor tests for `ResetPassword.vue`
- [x] clean up: search for `Wolle`

### Parent Branch

Is now sub branch of #1693 

----

_**[Tirokk](https://github.com/Tirokk)** included the following code: https://github.com/gradido/gradido/pull/1858/commits_
