### ISSUE TITLE
[CLOSED] refactor: 🍰 Create Filter Object in GQL And Rename Args

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1919]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Tuesday May 03, 2022 at 07:32 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1860_

----

## 🍰 Pullrequest

Create filter object in GQL and rename args.

### Issues

- fixes #1840

### Todo

- [x] ask @Mogge where the error comes from
- [x] rename all `filterBy*` to `by*`? will be done by sub PR
  - because all parameters are now in a `filters` object which looks like `filters.filterByDeleted`. 
  - nicer maybe is something like`filters.byDeleted`?
  - all agree to rename! i'll do in sub PR #1914 
- [x] test seeding manually
- [x] test `Creations.vue`
- [x] in other filter rename `withDeleted` to `filterByDeleted` etc.
- [x] in other filter rename `withExpired` to `filterByExpired` etc.
- [x] in other filter rename `withRedeemed` to `filterByRedeemed` etc.
- [x] set backend coverage to 66%
- [x] cleanup: search for `Wolle`

#### Sub PR

see #1914 

----

_**[Tirokk](https://github.com/Tirokk)** included the following code: https://github.com/gradido/gradido/pull/1860/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Tuesday May 03, 2022 at 07:36 GMT_

----

Hey @Mogge ,

I start renaming the filter properties and immediatelly get an error displayed in the editor in line:
https://github.com/gradido/gradido/blob/5fd1a86af1f5efa514b01784750830380fd53c0f/backend/src/graphql/resolver/AdminResolver.ts#L152

I like to know where this comes from.

Do I just have to rename the rest es well and then it will vanish?
Same happens at other parts of the code as well …

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Thursday May 19, 2022 at 09:17 GMT_

----

The one and only open question is if we like to rename the filter properties, see description:

> - [x] rename all `filterBy*` to `by*`?
>   - because all parameters are now in a `filters` object which looks like `filters.filterByDeleted`. 
>   - nicer maybe is something like`filters.byDeleted`?
