### ISSUE TITLE
[CLOSED] 🍰 Hide Pagenation On Short Transactionlist

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1934]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Thursday May 05, 2022 at 12:13 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1875_

----

## 🍰 Pullrequest

Hide pagenation on short transactionlist.

### Issues

- fixes #1804

### Todo

- [x] for seeding give bob@baumeister.de 28 transactions to show pagination on transaction list
- [x] Gradido account sum does not fit to the sum of the seeded transaction: see https://github.com/gradido/gradido/pull/1875#issuecomment-1118608209
  - we have a quick fix for that, see https://github.com/gradido/gradido/pull/1875/commits/c10115397568550cfaf69eb5317a97e2f8e0f049
- [x] add tests
- [x] clean up: search `Wolle`

----

_**[Tirokk](https://github.com/Tirokk)** included the following code: https://github.com/gradido/gradido/pull/1875/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Thursday May 05, 2022 at 14:14 GMT_

----

### Problem

GDD sum does not fit to the transactions in the list.

<img width="666" alt="Bildschirmfoto 2022-05-05 um 13 55 20" src="https://user-images.githubusercontent.com/25344101/166920910-4014af3c-e841-4c89-904e-8e34214a7f96.png">

<img width="1920" alt="Bildschirmfoto 2022-05-05 um 13 56 14" src="https://user-images.githubusercontent.com/25344101/166921418-963b6e6b-a21f-4129-86a9-95646e692d29.png">

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Thursday May 05, 2022 at 14:19 GMT_

----

@Mogge has responded on this in the Discord dev channel today at the 05.05.2022 at  15:50h.
Thanks a lot!

His suggested quick fix works, see https://github.com/gradido/gradido/pull/1875/commits/c10115397568550cfaf69eb5317a97e2f8e0f049
