### ISSUE TITLE
[CLOSED] 1887 [WIP] feature federation 09 create database and typeorm model

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1950]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Thursday May 12, 2022 at 10:31 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1891_

----

### Issues

- None

### Todo

- [x] backend-config for DB version check is open
- [ ] linting of database creates a lot of changes, so don't dare to commit
- [ ] can't find an existing relation OneToMany <-> ManyToOne as template, so a new solution is created, pleasse check this

----

_**[clauspeterhuebner](https://github.com/clauspeterhuebner)** included the following code: https://github.com/gradido/gradido/pull/1891/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Friday Nov 11, 2022 at 11:04 GMT_

----

this PR is deprecated, replaced by #2339 and will be closed now
