### ISSUE TITLE
[CLOSED] refactor: 🍰 Refactor To `filters` Object And Rename Filters Properties

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1973]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Thursday May 19, 2022 at 15:19 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1914_

----

## 🍰 Pullrequest

Refactor to `filters` object and rename filters properties.

### Issues

- relates #1840
- fixes #1913

### Todo

- all agree so rename:
  - [x] `filterByActivated`
  - [x] `filterByDeleted`
  - [x] `filterByExpired`
  - [x] `filterByRedeemed`
- [x] refactor to use `filters` object in frontend Vue's
  - [x] still todo on `Creation.vue` + manual tests
  - [x] still todo on `Creation.spec.js` + manual tests
  - [x] still todo on `UserSearch.vue` + manual tests
  - [x] still todo on `UserSearch.spec.js` + manual tests
- [x] try on `SearchUsersFilters` to remove the `ObjectType` after @Mogge suggestion
- [x] rename `convertObjValuesToArray` to `objectValuesToArray` after @Mogge suggestion
- [x] `SearchUsersFilters.ts` and `TransactionLinkFilters.ts`: is `?` and `| null` needed?
  - [x] is not needed! so remove it
  - [x] test transaction link creation and redeem manually
  - [x] test admins transaction links listing manually
- [x] `searchUsers`
  - [x] should `currentPage` start with `1` instead of `0`? i don't think so! make new issue?
    - [x] no, we decided
    - [x] created issue #1928 , is closed
- [x] `listTransactionLinksAdmin`
  - [x] should `currentPage` start with `1` instead of `0`? i don't think so! make new issue?
    - [x] no, we decided
    - [x] created issue #1928 , is closed
  - [x] write test
    - [x] have written some tests, but have to much questions
    - [x] `byExpired`
    - [ ] `byRedeemed`:
      - works not as expected, because 'redeemedAt' and 'redeemedBy' have to be added to the transaktion link factory. if you @Mogge like to do, please let it do together
  - [x] should be `byDeleted` named `withDeleted`, because it works different as in `searchUsers`?
  - [x] `filters`: shall I make it nullable?
    - done
- [x] move `searchUsers` query from mutation to query file
- [x] clean up: search for `Wolle`

----

_**[Tirokk](https://github.com/Tirokk)** included the following code: https://github.com/gradido/gradido/pull/1914/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Monday May 23, 2022 at 11:18 GMT_

----

I have several open Questions @Mogge , see open checks in the description and comments with `Wolle` in the PR.
I like to have this discussed with you …

I adjusted the backend test minimum to 68% … 😝

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Wednesday Jun 01, 2022 at 07:53 GMT_

----

> https://github.com/gradido/gradido/pull/1914#discussion_r885693554

@Mogge I'm very sorry! 🙏🏼
Couldn't think that one (JS) counts month from `0` to `11` and days from `1` to `31`.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Wednesday Jun 01, 2022 at 08:32 GMT_

----

> https://github.com/gradido/gradido/pull/1914#discussion_r885691559

@Mogge 
If it would work then the transaction link `Leider wollte niemand meine Gradidos zum Neujahr haben :(` should be in the response, but it isn't!
