### ISSUE TITLE
[CLOSED] 🔧 [Refactor] `currentpage` Should Start With `0` Instead of `1`

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1987]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Tuesday May 24, 2022 at 08:05 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/1928_

----

## 🔧 Refactor ticket

`currentpage` should start with `0` instead of `1`.

### Todo

- [ ] `searchUsers`
  - [ ] should `currentPage` start with `1` instead of `0`
  - [ ] `SearchUsersArgs`:
    - [ ] remove `?` from `currentPage` and `pageSize`
      - [ ] make them unullable
    - [ ] have a pagination InputType?
- [ ] `listTransactionLinksAdmin`
  - [ ] should `currentPage` start with `1` instead of `0`? i don't think so! make new issue?
  - [ ] `filters`: shall be nullable?
  - [ ] have a pagination InputType?

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Mogge"><img src="https://avatars.githubusercontent.com/u/15882241?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mogge](https://github.com/Mogge)**
_Wednesday May 25, 2022 at 05:04 GMT_

----

This is no good idea. Look at this (`frontend/src/components/Transactions/TransactionLinkSummary.vue`):
```
      if (this.currentPage === 0) {
        this.transactionLinks = []
        this.currentPage = 1
      }
```
We have a working mechanism. Please do not change this. There is no need to do this.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Wednesday May 25, 2022 at 08:41 GMT_

----

I wouldn't put specialities of bootstrap into the backend, but I accept if you @Mogge and @ogerly have a different opinion.
Okidoki 😉
