### ISSUE TITLE
[CLOSED] refactor: 🍰 Delete `user_setting` Table From DB

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2019]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Wednesday Jun 01, 2022 at 10:09 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1960_

----

## 🍰 Pullrequest

Delete `user_setting` table from db.

### Issues

- fixes #1948

### Question

Is this really clever to do?
Because we will need user settings in the future.

If I would do it consequently I would have to remove the class `UserSetting` and all related stuff as well.
We would have to implement it new in the future.

### Todo

- [x] fixed linting of database `README.md`
- [x] remove `UserSetting` and all related stuff?
  - search for:
    - [x] `UserSetting`
    - [x] `UserSettingRepository`
    - [x] `user_setting`
- [x] questions:
  - [x] should file `database/entity/UserSetting.ts` be deleted or shall it stay for ever?
    - [x] i have renamed all the imports from `../UserSetting` to `../0002-add_settings/UserSetting`. is that correct in case?
  - [x] is the reference in `database/entity/0002-add_settings/UserSetting.ts` for the user import lasst fitting one? or was it if unchanged with the actual `../User` correct?
- [x] cleanup: search for `Wolle`

----

_**[Tirokk](https://github.com/Tirokk)** included the following code: https://github.com/gradido/gradido/pull/1960/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Wednesday Jun 01, 2022 at 10:26 GMT_

----

This is how the db looks if a user setting is set:

<img width="1646" alt="Bildschirmfoto 2022-06-01 um 12 23 07" src="https://user-images.githubusercontent.com/25344101/171383879-e1e602b9-7c08-47c9-9620-8f7e8413e79c.png">
