### ISSUE TITLE
[CLOSED] refactor: 🍰 Not Throwing An Error When Register With Existing Email

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2021]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Wednesday Jun 01, 2022 at 13:48 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1962_

----

## 🍰 Pullrequest

Not throwing an error when register with existing email.

### Issues

- fixes #1880

### Todo

- [x] search for `User already exists.`
- [x] backend:
  - [x] email:
    - [x] send support link or email adress in email?
    - [x] put support in CC?
      - no!
      - test: `backend/src/mailer/sendEMail.test.ts` – yes
        - [x] should CC have an own test or is it okay just to add it to the existing?
          - no extra test!
    - [x] what is `backend/.env.template` really for?
      - [x] I added `EMAIL_LINK_FORGOTPASSWORD` there. is this fix okay?
  - [x] test
    - [x] `createUser` resolver: test refactor
    - [x] sendAccountMultiRegistrationEmail.ts
- [x] frontend:
  - [x] remove error from frontend
  - [x] is it okay to remove `commitStorePublisherId` from `Register.vue`? it seems not to be called at all @ogerly 
- [x] cleanup: search for `Wolle`

----

_**[Tirokk](https://github.com/Tirokk)** included the following code: https://github.com/gradido/gradido/pull/1962/commits_
