### ISSUE TITLE
[CLOSED]  feat: 🍰 Set Role In Admin Interface

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2033]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Wednesday Jun 08, 2022 at 12:46 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1974_

----

### Issues

- fixes #1881

### Todo

- [x] remove terminus `right`
- [x] backend:
  - [x] add `UserAdmin` update resolver mutation
  - [x] writing tests
- [x] frontend:
  - [x] have a column in the table that describes the role: I created issue #1980
    - [x] search for users with role: I created issue #1980
  - [x] localize selectable roles
  - [x] add GraphQL mutation for `UserAdmin` update resolver and use it
  - [x] writing tests
    - [x] test emit`updateIsAdmin`
    - [x] problem testing `toasts an error message`
- [x] cleanup: search for `Wolle`

----

_**[Tirokk](https://github.com/Tirokk)** included the following code: https://github.com/gradido/gradido/pull/1974/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Tuesday Jun 14, 2022 at 06:43 GMT_

----

Questions to @Mogge and @clauspeterhuebner , see description 👆🏼:

- Shall we have a column that shows the role?
  - Maybe create a new issue?
- Shall we have the ability to search for users with a role?
  - I guess then we have to create a new issue!?

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Tuesday Jun 14, 2022 at 09:21 GMT_

----

> Questions to @Mogge and @clauspeterhuebner , see description 👆🏼:
> 
>     * Shall we have a column that shows the role?
>       
>       * Maybe create a new issue?
> 
>     * Shall we have the ability to search for users with a role?
>       
>       * I guess then we have to create a new issue!?

This is answered and I created an issue: #1980
