### ISSUE TITLE
[CLOSED] 1794 feature event protocol 1 implement the basics of the business event protocol

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2056]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Tuesday Jun 21, 2022 at 02:38 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/1997_

----

### Issues

- None

### Todo

- [X] database table event_protocol created
- [X] database table enum_event_type created and populate key-value entries with description
- [X] entities for each table created
- [X] migration up and down ready
- [X] using nodejs events modul
- [X] EventProtocol class with write method for all EventProtocolType classes

----

_**[clauspeterhuebner](https://github.com/clauspeterhuebner)** included the following code: https://github.com/gradido/gradido/pull/1997/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Mogge"><img src="https://avatars.githubusercontent.com/u/15882241?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mogge](https://github.com/Mogge)**
_Friday Jul 01, 2022 at 15:34 GMT_

----

We have to find a way to start only one event listener for the unit tests. By now, each test (11) starts an event listener. So we get the warning that we have too much (11) event listeners.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Thursday Jul 07, 2022 at 01:03 GMT_

----

reworked all PR-comments...
The EventEmitter and the nodejs-modul 'events' are removed, but during the backend tests the MaxListener-Warning still exists...
