### ISSUE TITLE
[CLOSED] End-to-end test setup

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2106]
<a href="https://github.com/mahula"><img src="https://avatars.githubusercontent.com/u/3883288?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mahula](https://github.com/mahula)**
_Tuesday Jul 12, 2022 at 14:47 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2047_

----

## 🍰 Pullrequest

Set up ready-to-use Docker containers for end-to-end testing.

At the moment we play around with the two frameworks Cypress and Playwright.

### Issues

- relates #162

### Todo
- [x] Set up a ready-to-use configuration for a Docker container each (Cypress and Playwright)
- [x] Configure the containers to run the tests against a locally running DEV system
- [x] Implement the happy path login test for each framework container
- [x] Connect e2e test container to host network (localhost)

----

_**[mahula](https://github.com/mahula)** included the following code: https://github.com/gradido/gradido/pull/2047/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Tuesday Jul 12, 2022 at 14:57 GMT_

----

Seems already quite nice, my first questions would be:
- You use JS in Cypress and TypeScript in Playwright is their a reason for this? 
- Does Cypress only understand JS? Or could it also be written in TS?

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/mahula"><img src="https://avatars.githubusercontent.com/u/3883288?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mahula](https://github.com/mahula)**
_Tuesday Jul 19, 2022 at 11:17 GMT_

----

> Seems already quite nice, my first questions would be:
> 
> * You use JS in Cypress and TypeScript in Playwright is their a reason for this?
> * Does Cypress only understand JS? Or could it also be written in TS?

Cypress tests can also be written in Typescript (see [here](https://docs.cypress.io/guides/tooling/typescript-support)). From now on we will write the Cypress tests in Gherkin and TS.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/mahula"><img src="https://avatars.githubusercontent.com/u/3883288?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mahula](https://github.com/mahula)**
_Friday Sep 23, 2022 at 11:20 GMT_

----

> I get this errors when executing the tests:
> 
> ```
> libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
> [480:0922/081004.434283:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
> ```

These two errors have no impact on the cypress test execution.
They are related to graphic components not available when running in CI or Docker containers.
This can be adressed in a separat issue.
