### ISSUE TITLE
[CLOSED] GradidoID 1: adapt and migrate database schema

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2117]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Friday Jul 15, 2022 at 00:50 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2058_

----

### Issues

- None

### Todo

- [X] create new table user_contacts
- [X] change existing table users
- [X] adapt User and create UserContact entity
- [X] adapt UserResolver, UserResolverTest and seeding
- [X] Gradido-ID as UUID is created and set during creating a new user-entry on database level
- [X] Migration of existing Email-Data (email, emailChecked) to a new entry in user_contacts table including inserting the user_contacts.id as email_id in the users table
- [X] all backend refactorings including tests and seeding on new data structure; yes it was planned in the issue #2165 , but it causes problems to checkin only database changes without backend migrations; there exists a smaller ticket and PR (#2126) for only the gradidID and alias migrations

----

_**[clauspeterhuebner](https://github.com/clauspeterhuebner)** included the following code: https://github.com/gradido/gradido/pull/2058/commits_
