### ISSUE TITLE
[CLOSED] feat: 🍰 Send Email To Transaction Link Sender After Receiver Redeemed It

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2122]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Tuesday Jul 19, 2022 at 10:15 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2063_

----

## 🍰 Pullrequest

When a user redeems a transactionLink add a method that sends an email to the sender of the redeemed code.

### Issues

- fixes #2010 

### Todo

- [X] Add text of the email that needs to be send
- [X] Add method that gets the informations to whom it should be send
- [X] Add send email to sender if transactionLink is present.

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/2063/commits_
