### ISSUE TITLE
[CLOSED] chore: 🍰 Provide Volume For Backend Log-Files In Docker

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2126]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Thursday Jul 21, 2022 at 09:08 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2067_

----

Provide volume for backend log-files in Docker.

### Issues

- fixes #1904

### Additional Informations

see https://stackoverflow.com/questions/42248198/how-to-mount-a-single-file-in-a-volume

### Todo

- [x] move provision of volume for ngnix from dev Docker Compose file to main
- [x] are the important log-files which I couldn't find as well for:
  - [x] database
    - is already in `database/typeorm.backend.log`
  - [x] frontend
    - nothing
  - [x] admin
    - nothing
  - [x] mariadb
    - [x] maybe: `/var/log`? I added this
      - but I can't see any logings
      - @mogge says we don't need this

----

_**[Tirokk](https://github.com/Tirokk)** included the following code: https://github.com/gradido/gradido/pull/2067/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Mogge"><img src="https://avatars.githubusercontent.com/u/15882241?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mogge](https://github.com/Mogge)**
_Thursday Jul 21, 2022 at 09:46 GMT_

----

We have a `logs` folder, which is ignored by git. Inside this folder, there is a `backend` folder, which has four files:
```
access.log
apollo.log
backend.log
errors.log
```
When you run the seeds or unit tests locally, these files are appended. When you run the backend locally as well. When you run the backend in docker these files are not touched.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Mogge"><img src="https://avatars.githubusercontent.com/u/15882241?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mogge](https://github.com/Mogge)**
_Thursday Jul 21, 2022 at 09:48 GMT_

----

The database log is in `database/typeorm.backend.log`. This works fine with docker.
Admin and Frontend have no Logs.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Thursday Jul 21, 2022 at 09:59 GMT_

----

> The database log is in `database/typeorm.backend.log`. This works fine with docker.
Admin and Frontend have no Logs.

Then I mirror this file as well into the general logs folder … @Mogge

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Thursday Jul 21, 2022 at 11:37 GMT_

----

https://github.com/gradido/gradido/pull/2067#issuecomment-1191276837
I understood this. @Mogge 

But with the `database/typeorm.backend.log` file it works from Docker somehow it looks like …

I pushed the new code …

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Thursday Jul 21, 2022 at 13:56 GMT_

----

!!! Please test crutial before you merge. @Mogge 

It has worked in the morning for the backend and works still for nginx, but now it does not work for the backend at the moment and I can not figure out why.

I restarted everything …

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Thursday Jul 21, 2022 at 15:56 GMT_

----

!!! Please test crutial before you merge. @Mogge 

It has worked in the morning for the backend and works still for nginx, but now it does not work for the backend at the moment and I can not figure out why.

I restarted everything …

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Monday Jul 25, 2022 at 10:07 GMT_

----

Now it should work as expected … @Mogge
