### ISSUE TITLE
[CLOSED] Fix: Test memo length on createContribution & updateContribution

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2139]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Monday Jul 25, 2022 at 09:30 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2080_

----

## 🍰 Pullrequest

Checks if the memo length that is send to createContribution & updateContribution mutation is correct (greater than 5 and smaller than 255 chars)

### Issues
- fixes #2076 

### Todo

- [X] createContribution checks if 5 ≤ memo.length ≤ 255
- [X] updateContribution checks if 5 ≤ memo.length ≤ 255
- [X] Unit Test createContribution throws error if length to small or to big
- [X] Unit Test updateContribution throws error if length to small or to big

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/2080/commits_
