### ISSUE TITLE
[CLOSED] fix: 🍰 Reset Amount In Contribution Form And Write A Test

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2145]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Monday Jul 25, 2022 at 12:09 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2086_

----

## 🍰 Pullrequest

Reset amount in contribution form and write a test etc.

See:

<img width="1646" alt="Bildschirmfoto 2022-07-25 um 12 26 02" src="https://user-images.githubusercontent.com/25344101/180771612-decd1388-d576-4573-8a11-f48d9e31319d.png">

And:

<img width="1646" alt="Bildschirmfoto 2022-07-25 um 12 26 57" src="https://user-images.githubusercontent.com/25344101/180771701-d546c9e0-65c1-4815-a0a0-be365edc373c.png">

### Issues

- fixes #2084

### Todo

- [x] contribution form does not reset amount after submit
- [x] submit button shall be named `Change`
- [x] after submit on `Change` (with `id`) `Change` button text shall change to `Submit`
- [x] there shall be a `Cancel` button

----

_**[Tirokk](https://github.com/Tirokk)** included the following code: https://github.com/gradido/gradido/pull/2086/commits_
