### ISSUE TITLE
[CLOSED] chore: 🍰 Refactor Contribution Form Logic And Write Tests

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2151]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Tuesday Jul 26, 2022 at 14:23 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2092_

----

## 🍰 Pullrequest

Refactor contribution form logic and write tests.

### Issues

- fixes #2091

### Todo

- [x] refine logic of `lastMonthObject` etc.
- [x] check year in `isThisMonth`
- [x] test it
  - [x] partly
- [x] test for memo length (use constant)
  - [x] < 5
  - [x] >= 5 <= 255
  - [x] > 255
- [x] cleanup: search for `Wolle`

----

_**[Tirokk](https://github.com/Tirokk)** included the following code: https://github.com/gradido/gradido/pull/2092/commits_
