### ISSUE TITLE
[CLOSED] 2125 feature gradido id: new column gradidoid in users table

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2185]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Tuesday Aug 09, 2022 at 21:51 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2126_

----

### Issues

- None

### Todo

- [X] new column gradidoID in users table
- [X] new column alias in users table
- [X] adapt entity DbUser to new columns
- [X] install package uuid in database and backend modul
- [X] new migration script to generate for each existing user-entry a valided unique UUID-V4
- [X] add in UserResolver the generation of a valided unique UUID-V4 during createUser invokation
- [X] add in UserResolverTest the additional columns and the UUID-Validation on correct version and validation
- 

----

_**[clauspeterhuebner](https://github.com/clauspeterhuebner)** included the following code: https://github.com/gradido/gradido/pull/2126/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Mogge"><img src="https://avatars.githubusercontent.com/u/15882241?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mogge](https://github.com/Mogge)**
_Tuesday Aug 16, 2022 at 08:53 GMT_

----

> Do we have the backend version to increment?
@Tirokk We only have to increment the backend version when the `.env` changes. This is not the case here.
