### ISSUE TITLE
[CLOSED] feat(backend): 🍰 Email Templates

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2222]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Wednesday Aug 24, 2022 at 09:08 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2163_

----

## 🍰 Pullrequest

Email templates.

### Issues

- fixes #1288

### Todo

- [x] questions:
  - [x] add a config to open send emails in the browser?
    - [x] the emails content is logged out anyways
    - [x] on macOS I get an error openning Firefox …
  - [x] do we want to have `HTML` and `text` in the mails?
    - is automatically at our configuration
  - [x] email content:
    - [x] `sendAccountMultiRegistrationEmail`:
      - [x] whos name shall appeare in the salutation:
        - [ ] ~~the name of the new registrant?~~
        - [x] or the name of the registered owner of the email?
- [x] set `i18n` logger functions?
  - [ ] but I haven't found if it works
- [ ] replace `i18n` `__` function by `t`?
- [x] set `i18n` language globaly for a user?
  - [x] is the language handled separately for each user really?
    - @Mogge says yes
  - [x] on create user
  - [x] on update user
  - [x] on login user
- [x] seeding is hanging on its end
  - this happens if we set `autoReload: true` on `i18n` in `createServer`
- [x] add `yarn locales --fix` for the backend? -> issue #2366 
- [ ] tests:
  - [ ] test `backend/src/graphql/resolver/UserResolver.test.ts`
    - [ ] call of `i18n.setLocale()`
  - [x] writing new ones
  - [x] have a look at `sends an account multi registration email` in file `src/graphql/resolver/UserResolver.test.ts`
    - because sometimes on my macOS it opens the browser and the iPhone simulator to preview the send mail
- [x] remove the old `sendAccountMultiRegistrationEmail` email
- [x] remove `backend/src/mailer/text/accountMultiRegistration.ts`
- [x] add good descriptions to the readme or delete it
- [x] cleanup: search for `Wolle`

----

_**[Tirokk](https://github.com/Tirokk)** included the following code: https://github.com/gradido/gradido/pull/2163/commits_
