### ISSUE TITLE
[CLOSED] Add is moderator to contribution message

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2239]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Tuesday Sep 06, 2022 at 12:38 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2180_

----

## 🍰 Pullrequest
To have a difference in the contribution messages between user message and admin message we add a is_moderator field to the contribution_messages table. 

### Issues

- None

### Todo

- [X] Create new migration that adds is_moderator to the database
- [X] Add new field isModerator to ContributionMessage entity
- [X] Add new isModerator Field to ContributionMessage graphql model
- [X] Set value on isModerator for the two calls adminCreateContributionMessage => true, createContributionMessage => false

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/2180/commits_
