### ISSUE TITLE
[CLOSED] [WIP] 2176 architecture document of access layer

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2249]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Friday Sep 09, 2022 at 14:11 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2190_

----

### Issues

- fixes #2176

### Todo

- [X] analyse the current resolver dependencies
- [X] analyse for each resolver the used backend components
- [X] design a first draft for a new data access layer to encapsulate typeorm and database technics from resolver access
- [X] future prospects of refactoring concerning multi community readyness

----

_**[clauspeterhuebner](https://github.com/clauspeterhuebner)** included the following code: https://github.com/gradido/gradido/pull/2190/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Thursday Dec 01, 2022 at 20:30 GMT_

----

@clauspeterhuebner can we get this ready for merge please?

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Friday Jun 09, 2023 at 10:16 GMT_

----

close it because of missing interest in the team about more modularity and structure... :(
