### ISSUE TITLE
[CLOSED] fix(backend): wrong month for contribution near turn of month

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2260]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Wednesday Sep 14, 2022 at 20:07 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2201_

----

### Issues

- None

### Todo

- [X] analysis of problem with user timezone offset
- [X] examples as base for discussion in architecture meeting
- [X] decisions
- [X] analysis of all resolver methods / exported attributes concerning the user timezone offset
- [X] this PR will be solved by issue #2225 and PR #2229 

----

_**[clauspeterhuebner](https://github.com/clauspeterhuebner)** included the following code: https://github.com/gradido/gradido/pull/2201/commits_
