### ISSUE TITLE
[CLOSED] docs: 🍰 Refine Deployment Documentation

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2268]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Thursday Sep 15, 2022 at 13:36 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2209_

----

## 🍰 Pullrequest

Refine deployment documentation.

### Issues

- fixes #2208

### Todo

- [x] it's missing that all the variables in `/home/gradido/gradido/deployment/bare_metal/.env` have to be set before we go to `install.sh`
  - [x] `.env` has to be copied from `.env.dist`
- [x] setting the local env variables by the script at the begining of `install.sh` didn't work
  - [x] give a hint of an alternative for direct use in the terminal

----

_**[Tirokk](https://github.com/Tirokk)** included the following code: https://github.com/gradido/gradido/pull/2209/commits_
