### ISSUE TITLE
[CLOSED] reconfig log4js with rollover feature and userid in logevent-message

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2280]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Tuesday Sep 20, 2022 at 02:19 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2221_

----

### Issues

- None

### Todo

- [X] change log4js configuration to activate file-rollover daily
- [X] change log4js configuration to add userID in log-message
- [X] advice to call log4js.shutdown() before stopping the application/node.js 
       => shift it in a separate issue #2235 , because of necessary shutdown-hook for node.js; 
             see https://github.com/shaharke/shutdown-hook
- [X] setting the userID always correct in all backend-services
       => could be done on the fly during refactoring and development

----

_**[clauspeterhuebner](https://github.com/clauspeterhuebner)** included the following code: https://github.com/gradido/gradido/pull/2221/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Wednesday Sep 28, 2022 at 09:47 GMT_

----

Auf Stage-2 läuft nun der Code von Branch 2220-feature-reconfigure-log4js, um das RollOver-Feature von log4js zu verifizieren.
Im Verzeichnis /gradido/gradido/logs/backend sind die aktuellen LogFiles und die RollOver-Files aus dem Vortag mit dem letzten Log-Eintrag. WIe man sieht kann das auch mehrere Tage zurückliegen, da immer erst mit neuem Log-Eintrag gepürft wird, ob ein RollOver notwendig ist.
