### ISSUE TITLE
[CLOSED] 2225 feature use client time in server to request user creations for the last 3 month

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2288]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Wednesday Sep 21, 2022 at 20:23 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2229_

----

### Issues

- None

### Todo

- [X] get clientRequestTime from context and if it not exists use current backend time
- [X] introduce the clientRequestTime as parameter to query the creations
- [X] adopt the query-changes from #2202
- [X] exchange the used date in the query with the clientRequestTime
- [X] several tests with clientRequestTime in the future against the backend time
- [X]  additional tests with clientRequestTime in the past against the backend time

----

_**[clauspeterhuebner](https://github.com/clauspeterhuebner)** included the following code: https://github.com/gradido/gradido/pull/2229/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Wednesday Nov 02, 2022 at 16:53 GMT_

----

fixes #2225 ?

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Thursday Nov 03, 2022 at 16:18 GMT_

----

The End-To-End Tests fail, because this PR will be blocked by the issue #2326 to adapt the frontend on the backend api changes.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Thursday Nov 17, 2022 at 23:44 GMT_

----

this PR will be closed, because of solution with #2393

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Thursday Nov 24, 2022 at 20:30 GMT_

----

On my opinion we can close this PR, because Moritz created a better solution to solve the timezone topic.

This PR contains additional features like savings in database and graphQL API changes to deliver the structured object ContributionMonth with amount and month to the frontend.

The branch should NOT be deleted to keep the possiblility to have a look on code later...
