### ISSUE TITLE
[CLOSED] Refactor: Contribution resolver logs and events

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2290]
<a href="https://github.com/jjimenezgarcia"><img src="https://avatars.githubusercontent.com/u/99907380?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jjimenezgarcia](https://github.com/jjimenezgarcia)**
_Thursday Sep 22, 2022 at 10:09 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2231_

----

## 🍰 Pullrequest
- Added tests for error logs
- Added tests for events saving
- Added event saving in contribution resolver

### Issues
- fixes #2205 

### Todo
- [X] None
- [x] Add missing contribution delete and update events
- [x] Fix deletion, not working properly
- [x] Add all new events

----

_**[jjimenezgarcia](https://github.com/jjimenezgarcia)** included the following code: https://github.com/gradido/gradido/pull/2231/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Mogge"><img src="https://avatars.githubusercontent.com/u/15882241?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mogge](https://github.com/Mogge)**
_Friday Sep 23, 2022 at 16:28 GMT_

----

Please see: https://github.com/gradido/gradido/blob/master/docu/Concepts/TechnicalRequirements/BusinessEventProtocol.md

Update the new events in this document

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Mogge"><img src="https://avatars.githubusercontent.com/u/15882241?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mogge](https://github.com/Mogge)**
_Monday Oct 10, 2022 at 12:43 GMT_

----

Why is there a forced push?

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/jjimenezgarcia"><img src="https://avatars.githubusercontent.com/u/99907380?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jjimenezgarcia](https://github.com/jjimenezgarcia)**
_Tuesday Oct 11, 2022 at 09:37 GMT_

----

> Why is there a forced push?

because I duplicated my work in the already done push and in what I wrote, did a bit of mess so I prefered to avoid collisions.
