### ISSUE TITLE
[CLOSED] refactor: 🍰 Login And Logout To Mutations

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2291]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Thursday Sep 22, 2022 at 10:31 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2232_

----

## 🍰 Pullrequest

Since login and logout writes or will write events to the database, they are no queries anymore.
In this PR we changed them to mutations.

### Issues

- fixes #2218

### Todo

- [X] Backend change login to mutation
- [X] Backend change logout to mutation
- [X] Frontend change call to login 
- [X] Frontend change call to logout
- [X] Backend fix tests 
- [X] Frontend fix tests 

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/2232/commits_
