### ISSUE TITLE
[CLOSED] 2238 feature configure git to keep linebreaks on lf even on windows

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2298]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Monday Sep 26, 2022 at 16:43 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2239_

----

### Issues

- None

### Todo

- [X] add .gitattributes-file to switch off autocrlf off
- [X] set git configuration global and system core.autocrlf false
       * git config -l                  shows all configuration settings
       * git config -l --core        shows only the core sttings
       * git config -l --global     shows only the global settings
       * git config - l --system   shows only the system settings
       * git config -e                  opens an editor to change the property "core.autocrlf" from true to false
       * git config --system -e   opens an editor to change the system properties
- [X] added a simple helper script to update the important submoduls per yarn

----

_**[clauspeterhuebner](https://github.com/clauspeterhuebner)** included the following code: https://github.com/gradido/gradido/pull/2239/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Thursday Sep 29, 2022 at 22:25 GMT_

----

> What do you need this script for?

small helper script, because several times the application doesn't work based on missing or not updated yarn references. And after doing this several times manually i create this script.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Thursday Oct 06, 2022 at 20:12 GMT_

----

these changes must never be merged in master
