### ISSUE TITLE
[CLOSED] chore: 🍰 Fix Cypress Tests Unreliability

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2304]
<a href="https://github.com/mahula"><img src="https://avatars.githubusercontent.com/u/3883288?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mahula](https://github.com/mahula)**
_Wednesday Sep 28, 2022 at 13:25 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2245_

----

## 🍰 Pullrequest
Fix reliability issues and an error related to missing files

### Issues
- fixes #2243

### Todo
- [X] set wait time for URLs and elements higher
- [X] fix language dependence of several selectors in login and user profile tests
- [X] change script command for Cypress execution so it does not overwrite the option to use Cypress locally with its GUI
- [X] add missing registration test files

----

_**[mahula](https://github.com/mahula)** included the following code: https://github.com/gradido/gradido/pull/2245/commits_
