### ISSUE TITLE
[CLOSED] 1574 concept to introduce gradidoID and change password encryption

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2311]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Wednesday Oct 05, 2022 at 23:43 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2252_

----

### Issues

- None

### Todo

- [X] stage-1: introduction of new columns users.gradidoID, users.alias and new table user_contacts
- [X] stage-1: database migration to changed schema
- [X] stage-1: adapt business logic on changed schema
- [X] stage-2: introduction of new password encryption without email as input
- [X] stage-2: shift existing encryption logic in new structured xxxEncryptor classes
- [X] stage-2: support generalized Encryptor API for different Encryptor implementations now and in the future
- [X] stage-2: adapt the buinsess logic on the changed password encryption implementations 

----

_**[clauspeterhuebner](https://github.com/clauspeterhuebner)** included the following code: https://github.com/gradido/gradido/pull/2252/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Wednesday Nov 02, 2022 at 21:41 GMT_

----

> Is the user -> userContacts really a 1:1 relation? Why is the sense of this? 

  * the user has a 1:1 relation to user_contacts per users.email_id
  * the user has a 1:n relation to user_contacts per user_contacts.user_id
  * the 1:1 relation is used like the previous  user.email attribut as the "main email contact"
  * the 1.n relation is prepared for further user_contacts like several emails or a phone contact
 
 
> Why do you reference from user to userContacts not vice versa? Just in case we want to have multiple contacts in the future? 

  * see the answer above, there is a reference from user_contacts to users with the attribute user_contacts.user_id
 
> Why do you merge in the opt in code stuff when this is a totally different topic?
 
  * in the email_opt_in-tabel there were the following important attributes located: 
    * email_checked
    * email_send_count
    * email_verification_code
    * email_opt_in_type. 
  * So why should these attributes belongs to totally different topic than belonging to email?
 
> why was the alias introduced (marked as done) when its not implemented yet?
 
  * the attribute alias is still part of the users-table since introducing the gradido_id with the UUID-V4 in database-migration 046
  * the content for the attribute alias have to be captured by the user himself
  * the capturing alias process steps are designed in the concept #2144 and are still not reviewed nor implemented
 

> questions over questions 
 
  * but all with well designed and clear answers ;-)
