### ISSUE TITLE
[CLOSED] fix(backend): devops backend test for adminresolvers confirm two creations one after is flaky

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2314]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Friday Oct 07, 2022 at 19:35 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2255_

----

### Issues

- None

### Todo

i had several ideas to solve this problem:
- [X] introduce milliseconds in datetime columns to ensure correct order even when writing in the same second
- [X] enable the database to lock single row instead of whole table during write access by defining indexes; 
       described here: https://stackoverflow.com/questions/2332768/how-to-avoid-mysql-deadlock-found-when-trying-to-get-lock-try-restarting-trans
- [X] surround the write access with a retry logic to solve deadlocks of concurrent invocations of the same method; 
       described here: https://blog.tekenlight.com/2019/02/21/database-deadlock-mysql.html

All three ideas are implemented, but not till the third one with the retry logic solves the problem

----

_**[clauspeterhuebner](https://github.com/clauspeterhuebner)** included the following code: https://github.com/gradido/gradido/pull/2255/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Thursday Jan 12, 2023 at 14:27 GMT_

----

there is a better solution in #2458 
this PR will be closed
