### ISSUE TITLE
[CLOSED] 🌟 [RM-EPIC] New Design

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2349]
<a href="https://github.com/ogerly"><img src="https://avatars.githubusercontent.com/u/1324583?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ogerly](https://github.com/ogerly)**
_Monday Oct 24, 2022 at 07:17 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/2290_

----

This is where all the work and branches are pulled together. 

## 🌟 EPIC
The following issues are open 

- [ ] Framework  2003 basic framework template #2026 
- [ ] Menu 2004 basic menu #2033 
- [ ] Header 2005 basic header #2028 
- [ ] Content Area #2304
