### ISSUE TITLE
[CLOSED] add column clientRequestTime to contributions

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2384]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Wednesday Nov 02, 2022 at 15:30 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2325_

----

### Issues

- fixes #2324 

### Todo

- [X] 1st part: db migration
- [X] 2nd part: transfer the clientRequestTime from context through the backend in the database
- [ ] 3rd part: backend adaptions solved in #2225 
- [ ] 4th part: backend tests solved in #2225
- [ ] 5th part: frontend connection to changed backend api still open and adressed with issue #2326 

----

_**[clauspeterhuebner](https://github.com/clauspeterhuebner)** included the following code: https://github.com/gradido/gradido/pull/2325/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Wednesday Nov 02, 2022 at 21:34 GMT_

----

> Please use the symbol `clientRequestTime`, else we will have half an implementation lingering around.
 
Do you mean somewhere in the code or in the headline of this PR? If you mean in the code, then please add the comments in the corresponding file and line of code.

For database table and attribute names there is the naming convention not to use camelcase: So the database column is named client_request_time and in the TypeORM and models above it is named clientRequestTime.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Thursday Nov 24, 2022 at 20:22 GMT_

----

On my opinion we can close this PR, because Moritz created a better solution to solve the timezone topic.

This PR contains additional features like savings in database and special testcases.
The API-changes with ContributionMonth is part of the PR #2229 

The branch should NOT be deleted to keep the possiblility to have a look on code later...
