### ISSUE TITLE
🌟 [EPIC] Userstories

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2386]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Wednesday Nov 02, 2022 at 20:53 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/2327_

----

## 🌟 EPIC - Userstories

This issue serves to collect and complete our list of user stories to test our application

#### Sign In
  - [x] [User.Authentication.feature](https://github.com/gradido/gradido/blob/master/e2e-tests/cypress/tests/cypress/e2e/User.Authentication.feature) (happy path scenario)
    :question: what about moving this feature story to `User.Authentication.SignIn.feature` ?

#### Sign up 
  - [x] [User.Registration.feature](https://github.com/gradido/gradido/blob/master/e2e-tests/cypress/tests/cypress/e2e/User.Registration.feature) (happy path scenario)
    - :question: what about moving this feature story to `User.Authentication.SignUp.feature`?

#### Forgot password
  - [x] [User.Authentication.ResetPassword.feature](https://github.com/gradido/gradido/blob/master/e2e-tests/cypress/e2e/User.Authentication.ResetPassword.feature) (happy path scenario)

#### Redeem link
  - via sign in
  - via sign up

#### Transactions (SendCoin)
  - [x] [SendCoins.feature](https://github.com/gradido/gradido/blob/master/e2e-tests/cypress/e2e/SendCoins.feature) (happy path scenarios)
    - Send
    - Receive

#### Link
  - erzeugen
  - einlösen

- Contribution Link einlösen
- Contribution eintragen

- locals?

####  Change Password
  - [x] [UserProfile.ChangePassword.feature](https://github.com/gradido/gradido/blob/master/e2e-tests/cypress/tests/cypress/e2e/UserProfile.ChangePassword.feature) (happy path szenario)
