### ISSUE TITLE
[CLOSED] [WIP] 1801 feature gradidoid 21 adapt business logic orm mapping searchaccess identity mapping endecrypt password

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2390]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Friday Nov 04, 2022 at 02:05 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2331_

----

### Issues

- None

### Todo

- [X] database migration; ready
- [ ] encryptor classes; ongoing
- [ ] usage of the encryptor classes in resolvers; ongoing 

----

_**[clauspeterhuebner](https://github.com/clauspeterhuebner)** included the following code: https://github.com/gradido/gradido/pull/2331/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Thursday Nov 24, 2022 at 20:53 GMT_

----

I don't know if Joseji uses this PR as base for the new password encryptions in #2353 
So this PR will be closed, but the branch should NOT be deleted to keep the code for future
