### ISSUE TITLE
[CLOSED] refactor: [WIP] 🍰 Frontend Transactions – Use Apollo Client Correctly

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2400]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Monday Nov 07, 2022 at 09:53 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2341_

----

## 🍰 Pullrequest

Frontend use apollo client correctly/transactions.

### Issues

- fixes #2286

### Todo

- [ ] Integration tests:
  - [x] mock the apollo client
    - https://www.npmjs.com/package/mock-apollo-client
    - https://github.com/Mike-Gibson/mock-apollo-client
  - [ ] how to mock the error toaster?
    - see https://dev.to/n_tepluhina/testing-vue-apollo-2020-edition-2l2p
    - try to guess from https://apollo.vuejs.org/guide/testing.html#testing
- [x] in apollo provider:
  - [x] apply a default set of options? Like:
    - see https://apollo.vuejs.org/guide/apollo/special-options.html#special-options
    - see code below 👇🏼
  - [x] set default to `fetchPolicy: 'network-only'`
- [ ] Use Apollo queries and mutations directly in your templates?
  - [ ] \<ApolloQuery :query="/* some query */">
    - see https://apollo.vuejs.org/guide/components/#what-are-apollo-components
  - [ ] \<ApolloMutation
    - see https://apollo.vuejs.org/guide/components/mutation.html#apollomutation
- [ ] Caching:
  - [ ] Updating the cache
    - This works only if the object in the mutation result contains the __typename and id fields (or the custom fields you use to normalize the cache.
    - see https://apollo.vuejs.org/guide/components/mutation.html#updating-the-cache
  - [ ] normalize the cache – Configuring the Apollo Client cache
    - see https://www.apollographql.com/docs/react/caching/cache-configuration/#normalization
- [ ] cache statistics?
- [ ] cleanup: search for `Wolle`

#### Code

```js
const apolloProvider = new VueApollo({
  defaultClient: apolloClient,
  defaultOptions: {
    // apollo options applied to all queries in components
    $query: {
      loadingKey: 'loading',
      fetchPolicy: 'cache-and-network',
    },
  },
})
```

----

_**[Tirokk](https://github.com/Tirokk)** included the following code: https://github.com/gradido/gradido/pull/2341/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Mogge"><img src="https://avatars.githubusercontent.com/u/15882241?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mogge](https://github.com/Mogge)**
_Tuesday Jan 24, 2023 at 19:02 GMT_

----

Impossible to merge.
