### ISSUE TITLE
🐛 [Bug] Resend activation link must transport redeem-link / contribution-link

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2406]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Monday Nov 07, 2022 at 11:57 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/2347_

----

## 🐛 Bugreport

Resend activation link must transport redeem-link / contribution-link

Steps to reproduce
- [ ] Register with link
- [ ] Get activation EMail with link
- [ ] Activation-Link is expired
- [ ] Resend Activation loses link

Make sure to transport the link through activation even when requesting a new activation link
