### ISSUE TITLE
[CLOSED] refactor(backend): new password encryption implementation

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2412]
<a href="https://github.com/jjimenezgarcia"><img src="https://avatars.githubusercontent.com/u/99907380?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jjimenezgarcia](https://github.com/jjimenezgarcia)**
_Tuesday Nov 08, 2022 at 12:43 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2353_

----

## 🍰 Pullrequest
Modify password encryption strategy

### Issues

- fixes #2329
- fixes #1802
- relates #2331
- relates #1574

### Todo

- [x] Introduce a new field in the `user` table defining the `password_encryption_type` - this should be a tiny-int or similar.
- [x] the default value for `password_encryption_type` should be 1 for new accounts
- [x] Define an in-code enum for the password types
- [x] ecapsulate the old password encryption and decryption into its own file and define a universal interface for all mechanisms
- [x] build the new password mechanism which uses the Gradido_ID instead of the email. Use the same interface.

----

_**[jjimenezgarcia](https://github.com/jjimenezgarcia)** included the following code: https://github.com/gradido/gradido/pull/2353/commits_
