### ISSUE TITLE
[CLOSED] refactor(backend): new password encryption cleaning

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2454]
<a href="https://github.com/jjimenezgarcia"><img src="https://avatars.githubusercontent.com/u/99907380?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jjimenezgarcia](https://github.com/jjimenezgarcia)**
_Tuesday Nov 15, 2022 at 19:38 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2395_

----

## 🍰 Pullrequest
Set up the implementation so that it starts working as expected.

### Issues
- fixes #2329 
- relates #2353 

### Todo
- [x] The field `password_type` should be 1 for all existing contacts (which is email)
- [ ] on login update old passwords to the new mechanism (2)
- [ ] on register use the new mechanism only (2)

----

_**[jjimenezgarcia](https://github.com/jjimenezgarcia)** included the following code: https://github.com/gradido/gradido/pull/2395/commits_
