### ISSUE TITLE
[CLOSED] feat(backend): configs for additional instance of mariadb and backend on same server

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2455]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Tuesday Nov 15, 2022 at 21:06 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2396_

----

### Issues

- None

### Todo

This is a description of actions done within this PR on local machine outside the git-control:
- [X] as prerequisit from the directory "gradido" 
   - [X] a copy of the subdirectories "database", "mariadb" and "backend/ are created in the new directory "gradido2"
   - [X] a copy of the files ".env.local.dist", ".env.shell", "docker-compose.override.yml", "docker-compose.test.yml", "docker-compose.yml", "package.json" and "yarn.lock" are created in the directory "gradido2"
- [X] All changes of this PR are made in the new directory "gradido2" and are outside of the normal git-control to avoid any influence on the default configurations
- [X] the changes are then shifted under git-control in the directory "gradido/separate_instance" to keep them outside of the default configurations

----

_**[clauspeterhuebner](https://github.com/clauspeterhuebner)** included the following code: https://github.com/gradido/gradido/pull/2396/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Thursday Nov 24, 2022 at 20:15 GMT_

----

But where do you conserve the necessary changes of configuration for this additional instance on the same machine but different place?
If all the changes are done on the original files under git-control, you will overwrite the standard configuration as soon as you merge them.
You could create a separate document manually or create a script to change the necessary setting automatically.
But at the moment this was the KISS solution to save and communicate the changes for an additional instance running on the same machine.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Friday Jun 09, 2023 at 10:21 GMT_

----

close PR: misunderstanding and no requirement in the team to buildup several instances on one host even for development and test... :(
