### ISSUE TITLE
[CLOSED] refactor(backend): refactor more emails to translatables

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2457]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Thursday Nov 17, 2022 at 13:19 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2398_

----

## 🍰 Pullrequest

Refactor more emails to translatables.

### Issues

- fixes #2392
- fixes #1092

### Todo

- [x] `sendAccountActivationEmail`:
  - [x] set `duration` correct
- [x] translate:
  - [x] `Gradido (nicht antworten)`
- [x] fix production bug by copying email templates and locales into the build folder
- [x] test:
  - [x] in `sendEmailTranslated.test.ts` that `CONFIG.EMAIL_TEST_MODUS = true` replaces the receiver
    - like in the old test `backend/src/mailer/sendEMail.test.ts`
  - [x] `src/graphql/resolver/TransactionResolver.test.ts` fails
- [x] clean up: search for `Wolle`

----

_**[Tirokk](https://github.com/Tirokk)** included the following code: https://github.com/gradido/gradido/pull/2398/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Friday Dec 09, 2022 at 12:11 GMT_

----

> What happend to the plain text emails? Are they generated out of the HTML by the library or will the email just be HTML?

Plain text is generated out of the HTML. @ulfgebhardt
