### ISSUE TITLE
[CLOSED] feat(backend): deny contributions

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2520]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Tuesday Dec 13, 2022 at 09:16 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2461_

----

## 🍰 Pullrequest
Admin need a method to reject contributions instead of deleting them

### Issues

- fixes #2332 

### Todo

- [X] Create a method to rejectContribution (for admins)
- [X] Find contribution
- [x] Update contribution (state = rejected, rejectedAt = now, rejectedBy = adminUser.id, ...)
- [x] Save updatedContribution
- [x] Send EMail to user
- [x] wallet > my contributions > everything
- [x] wallet > community > accepted, rejected, pending
- [x] admin > user search > creation list > everything
- [x] admin > unconfirmed contributions > only pending
- [x] denied contributions must throw an error in `confirmContribution` in `backend/src/graphql/resolver/ContributionResolver.ts`

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/2461/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Friday Jan 13, 2023 at 12:34 GMT_

----

Admin Unit Test have to be reworked / fixed
Frontend Unit Test have to be rework / fixed
