### ISSUE TITLE
[CLOSED] feat(backend): design html emails and adjust texts

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2531]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Tuesday Dec 20, 2022 at 13:10 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2472_

----

## 🍰 Pullrequest

Design HTML E-Mails And Adjust Texts.

### Issues

- fixes #2466

### Todo

- [x] `CONFIG`:
  - [x] shall `SUPPORT_MAIL` be included and named `COMMUNITY_SUPPORT_MAIL`?
    - [x] backend
    - [x] frontend
    - [x] bare_metal
- [x] design
  - [x] create new issue for further design: #2473
  - [x] imprint
    - [x] with logo? (`frontend/img/brand/green.png`)
- [x] greeting formula:
  - [x] indivdual for each community:
    - [x] shall a new community change the locales?
- [x] add imprint:
  - [x] every community has its own imprint says @BerndHueckstaedt . so we make:
    - [x] explicit imprint in the locales?
    - [ ] link to the imprint?
      - if so do we put the URL into the
        - [ ] emails PUG file to be able to change the language part?
        - [ ] backend locales?
        - [ ] config?
- [x] (no) move `https://gradido.net/de/contact/` to locales?
  - [x] (yes) or shall it be replaced by the support email?
- [x] adjust tests

----

_**[Tirokk](https://github.com/Tirokk)** included the following code: https://github.com/gradido/gradido/pull/2472/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Thursday Dec 22, 2022 at 08:55 GMT_

----

@Tirokk Please consider to wait for the fake email server #2441 to be able to generate the emails more easily. Ask @mahula for details and merge shedule

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Tirokk](https://github.com/Tirokk)**
_Thursday Dec 22, 2022 at 12:07 GMT_

----

> @Tirokk Please consider to wait for the fake email server #2441 to be able to generate the emails more easily. Ask @mahula for details and merge shedule

I do not understand. Why? @ulfgebhardt 
There are no problems to generate the emails except to spend some time to go through all functions which are sending emails.

I have already done this and have the go for all emails from @BerndHueckstaedt and we can merge this after approve.
