### ISSUE TITLE
[CLOSED] 🚀 [Feature] Emails – Further Design Of HTML Emails

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2532]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Thursday Dec 22, 2022 at 07:32 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/2473_

----

## 🚀 Feature

Further Design Of HTML Emails with @Hardy-Hart-am-Start .

### Todo

- [ ] Emails dont use absolute bild address
- [ ] make the Logo transparent (maybe)
- [x] Emails communicate how long codes are valid (till when - timestamp)
- [x] Email `24 Stunden und 0 Minuten` should be `24 hours`.
- [x] maybe use PUGs block command instead of includes (yes please)
  - see https://pugjs.org/language/inheritance.html
- [ ] design
  - [x] have the Gradido logo?
  - [ ] new element
    - [ ] imprint
      - [ ] with logo? (`frontend/img/brand/green.png`)
