### ISSUE TITLE
[CLOSED] fix(backend): fix config - some typos

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2536]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Monday Dec 26, 2022 at 15:35 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2477_

----

## 🍰 Pullrequest

fix config
- [x] `ENV_NAME` present in config but never used
- [x] `FEDERATION_DHT_SEED` has a trailing space
- [x] `v14.2022-11-22` should be `v14.2022-12-22`
- [x] Check if versions are all correctly configured in all configs

### Issues

- fixes #2476

### Todo

- [X] None

----

_**[ulfgebhardt](https://github.com/ulfgebhardt)** included the following code: https://github.com/gradido/gradido/pull/2477/commits_
