### ISSUE TITLE
[CLOSED] feat(federation): implement a graphql client to request getpublickey

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2570]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Tuesday Jan 03, 2023 at 23:29 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2511_

----

### Issues

- None

### Todo

Implement in the backend modul:
- [X]  a logic as a trigger on new and reannounced communities
- [X]  a graphql-client for requesting getPublicKey
- [X]  invoke outof the trigger logic for each community the getPublicKey-Request
- [X]  save the result of the getPublicKey-Request in the community table
- [x]  think about versioning the requests - we might negotiate with a v.1.2 while we are on v.5.0

----

_**[clauspeterhuebner](https://github.com/clauspeterhuebner)** included the following code: https://github.com/gradido/gradido/pull/2511/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Friday Jan 27, 2023 at 21:53 GMT_

----

Hi @Mogge,
könntest du dir mal bitte den Test von backend/federation/validateCommunities.test.ts anschauen?
Da musst ich den Test für die Methode startValidationCommunities aktivieren, aber da wird in der Lookp ja der Timer verwendet und dieser zerschießt mir die DB-Connections und Pools.
Ohne diesen Test reicht die Coverage im Backend nicht und allen anderen noch ungetesteten Code im Verzeichnis backend/federation kann erst getestet werden, wenn das federation-modul mit seinen passenden graphql-endpoint steht und antwortet.
Oder hast noch eine andere Idee ausser die Coverage temporär zu reduzieren?
