### ISSUE TITLE
[CLOSED] feat(other): add description for daily backup cronjob

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2591]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Tuesday Jan 10, 2023 at 00:16 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2532_

----

### Issues

- fixes #1489

### Todo

- [X] daily backup cronjob on stage2
- [ ] daily backup cronjob on stage3
- [X] daily backup cronjob on production
- [X] add description in bare_metal/setup.md

----

_**[clauspeterhuebner](https://github.com/clauspeterhuebner)** included the following code: https://github.com/gradido/gradido/pull/2532/commits_
