### ISSUE TITLE
[CLOSED] feat(admin): reuse overlay on open contributions page for all 3 main admin actions confirm/delete/reject

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2608]
<a href="https://github.com/mahula"><img src="https://avatars.githubusercontent.com/u/3883288?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mahula](https://github.com/mahula)**
_Sunday Jan 15, 2023 at 12:27 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2549_

----

## 🍰 Pullrequest
At the moment the overlay is only used with the conrifmation action.
It should be used for three all main actions.

### Issues
- fixes #2370 

### Todo
- [X] adapt locales for all three actions
- [X] use the overlay for the three actions
- [x] adapt the submit button to emit the correct event in each case

----

_**[mahula](https://github.com/mahula)** included the following code: https://github.com/gradido/gradido/pull/2549/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ogerly"><img src="https://avatars.githubusercontent.com/u/1324583?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ogerly](https://github.com/ogerly)**
_Tuesday Jan 24, 2023 at 17:05 GMT_

----

An example of how to achieve the same functionality without a switch statement in Vue.js would be to use an object with key-value pairs, such as:


````
data() {
  return {
    overlay: false,
    item: null,
    overlayConfig: {
      confirm: {
        title: 'overlay.confirm.title',
        text: 'overlay.confirm.text',
        question: 'overlay.confirm.question',
        btnText: 'overlay.confirm.yes',
        event: this.confirmCreation
      },
      delete: {
        title: 'overlay.delete.title',
        text: 'overlay.delete.text',
        question: 'overlay.delete.question',
        btnText: 'overlay.delete.yes',
        event: this.removeCreation
      },
      reject: {
        title: 'overlay.reject.title',
        text: 'overlay.reject.text',
        question: 'overlay.reject.question',
        btnText: 'overlay.reject.yes',
        event: this.rejectCreation
      }
    }
  }
},

methods: {
  showOverlay(item, variant) {
    this.overlay = true
    this.item = item
    this.overlayTitle = this.overlayConfig[variant].title
    this.overlayText = this.overlayConfig[variant].text
    this.overlayQuestion = this.overlayConfig[variant].question
    this.overlyBtnText = this.overlayConfig[variant].btnText
    this.overlayEvent = this.overlayConfig[variant].event
  }
}

````

In this example, the overlayConfig object defines key-value pairs for each possible variant option that contain the same property values as in the switch example. In the showOverlay method, the value of variant is used to retrieve the corresponding property values from overlayConfig and assign them to the property values of the component.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ogerly"><img src="https://avatars.githubusercontent.com/u/1324583?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ogerly](https://github.com/ogerly)**
_Tuesday Jan 24, 2023 at 17:09 GMT_

----

An example of how to achieve the same functionality with a computed property in Vue.js might look like this:

``` 
data() {
  return {
    overlay: false,
    item: null,
    variant: 'confirm'
  }
},

computed: {
  overlayTitle() {
    return `overlay.${this.variant}.title`
  },
  overlayText() {
    return `overlay.${this.variant}.text`
  },
  overlayQuestion() {
    return `overlay.${this.variant}.question`
  },
  overlayBtnText() {
    return `overlay.${this.variant}.yes`
  },
  overlayEvent() {
    return this[`${this.variant}Creation`]
  }
},

methods: {
  showOverlay(item, variant) {
    this.overlay = true
    this.item = item
    this.variant = variant
  },
  confirmCreation() {
    // confirm creation logic
  },
  removeCreation() {
    // delete creation logic
  },
  rejectCreation() {
    // reject creation logic
  }
}
```

In this example, the overlayTitle, overlayText, overlayQuestion, overlayBtnText, and overlayEvent properties are defined as computed properties. Each computed property returns a value that is dynamically calculated based on the value of "variant". The showOverlay method is called to set the value of variant and item, which causes the computed properties to be recalculated and set the corresponding property values.
