### ISSUE TITLE
[CLOSED] 🚀 [Feature] Show all rejected & deleted contribution in AdminInterface

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2622]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Wednesday Jan 18, 2023 at 09:02 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/2563_

----

## 🚀 Feature

An admin can reject and delete contributions. If this has been done incorrectly then we need a page to show all contributions that have been rejected and another page for all deleted contributions. On each page we need to have a button to remove the reject or delet.
For deletion we want to remove the next properties (softDelete, deleted_at, deleted_by) and set the state back to open ('PENDING' or 'IN_PROGRESS')
For rejection we want to change the state back to open & remove the deny_at & deny_by)

## TODO
- [ ] Query for all rejected contributions
- [ ] Query for all deleted contributions
- [ ] Mutation for removeRejection
- [ ] Mutation for removeDeletion
- [ ] Page in admin to show all rejected contributions
- [ ] Page in admin to show all deleted contributions
- [ ] Test new pages
