### ISSUE TITLE
[CLOSED] 🚀 [Feature] [Admin] Contributions List

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2653]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Monday Jan 23, 2023 at 14:21 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/2594_

----

## 🚀 Feature

[Admin] Contributions List

Currently you can only access
- contributions per user
- open contributions

### TODOs
- [ ] Make the open contributions page always visible in the menu.
- [ ] The page must contain two tabs (open contributions, all contributions)
- [ ] if the open contributions contains items a red badge with the number of open contributions must be shown in the menu and on the tab, aswell as on the overview page.
- [ ] the `all contributions` must be ordered by the contribution with the last action on it (`updated_at`?) - e.g. confirmed, denied, deleted, ...
- [ ] additional tabs for filters are thinkable: `deleted`, `denied`, `confirmed`. All of those must be queried by the same graphQL query taking a list of filters(e.g. no filter = all, [' denied', 'confirmed'] for those two)
