### ISSUE TITLE
[CLOSED] feat(backend): add filterState parameter to listAllContributions query

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2678]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Tuesday Jan 24, 2023 at 11:06 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2619_

----

## 🍰 Pullrequest

Add a string or null parameter to the listAllContributions query, so that we can filter on statis ('DELETED', 'DENIED', ..., 'CONFIRMED')

### Issues

- fixes #2594 

### Todo

- [X] Add filterState array of ContributionStatus

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/2619/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Thursday Feb 02, 2023 at 08:22 GMT_

----

To do: Follow issue 
- [ ] Add IN_PROGRESS contributions in the database
- [ ] Add DENIED contributions in the database
- [ ] Add DELETED contributions in the database
