### ISSUE TITLE
[CLOSED] refactor(backend): unit test for the method denyContribution

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2698]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Tuesday Jan 31, 2023 at 12:27 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2639_

----

### Issues

- fixes #2653

### Todo

- [X] Test some cases
- [x] Test denyContribution of Contribution with not allowed state
- [ ] Have a contribution for a deleted user

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/2639/commits_
