### ISSUE TITLE
[CLOSED] Refactor: backend test add seeding for contributions 

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2712]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Thursday Feb 02, 2023 at 10:28 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/2653_

----

# Refactor
In the backend ContributionResolver we need some better tests.
Now we mock some answers and check that there is no contribution with wrong state, and now we need to add some contributions to better test it. 

# TODO 
- [ ] Add IN_PROGRESS contributions in the database
- [ ] Add DENIED contributions in the database
- [ ] Add DELETED contributions in the database

_Originally posted by @Elweyn in https://github.com/gradido/gradido/issues/2619#issuecomment-1413323752_
