### ISSUE TITLE
[CLOSED] feat(federation): harmonize and sync modules and data of federation

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2724]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Friday Feb 03, 2023 at 16:36 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2665_

----

### Issues

- None

### Todo

- [X] change database communities-table for homeCommunity-Entries
- [X] add dht-node federation-config properties for URL and default Port of Api-Version Endpoints
- [X] in dht-node insert HomeCommunity-Entry for each own supported Api-Version before starting dht-announcement
- [X] in dht-node change Api-Version to pure number without leading 'v', as expected for the Request getPublicKey in modul backend and federation
- [X] adapt and change communities-data send by dht-node to match the expected data by the backend-graphql-client from database for validating communities

----

_**[clauspeterhuebner](https://github.com/clauspeterhuebner)** included the following code: https://github.com/gradido/gradido/pull/2665/commits_
