### ISSUE TITLE
[CLOSED] refactor(other): don't rebuild modul if unit test file has been changed

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2726]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Monday Feb 06, 2023 at 14:37 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2667_

----

## 🍰 Pullrequest

As developer I don't want to rebuild modules if the test file has been changed. This PR fixes it

### Issues

- None

### Todo

- [X] Frontend: Block rebuild of docker (nodemon) when unit-test file
- [X] Admin: Block rebuild of docker (nodemon) when unit-test file
- [X] Backend: Block rebuild of docker (nodemon) when unit-test file

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/2667/commits_
