### ISSUE TITLE
[CLOSED] 🚀 [Feature] Backend – Emails – Adjust Namings of Menus to New Frontend Design

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2811]
<a href="https://github.com/Tirokk"><img src="https://avatars.githubusercontent.com/u/25344101?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Tirokk](https://github.com/Tirokk)**
_Tuesday Feb 28, 2023 at 06:47 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/2752_

----

## 🚀 Feature

Backend – E-Mails – Adjust Namings of Menus to New Frontend Design.

### Todo

- [x] change if design is already implemented or if necessary make issue for:
  - [x] reminder that the email texts have to be adjusted if the menu namings are changing with the new design for:
    - [x] contribution emails `addedContributionMessage`, `contributionRejected`:
      - [x] contribution menu will be renamed
        - search for:
          - de: `„Gemeinschaft“` and `„Meine Beiträge zum Gemeinwohl“`
          - en: `“Community”` and `“My contributions to the common good”`
