### ISSUE TITLE
[CLOSED] refactor(workflow): configure jest to directly check coverage to schlanken the test workflows

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2849]
<a href="https://github.com/mahula"><img src="https://avatars.githubusercontent.com/u/3883288?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mahula](https://github.com/mahula)**
_Tuesday Mar 07, 2023 at 16:11 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2790_

----

## 🍰 Pullrequest
We can configure jest to directly check coverage at the end of unit testing.
This makes the separate coverage check steps in our workflows obsolete.

### Todo
- [X] add `coveragaThreshold` to all `jest.condig.js`
- [X] remove separate coverage check steps from github test wirkflows
- [x] remove the coverage checks from the branch protection, @ulfgebhardt 

----

_**[mahula](https://github.com/mahula)** included the following code: https://github.com/gradido/gradido/pull/2790/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/mahula"><img src="https://avatars.githubusercontent.com/u/3883288?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mahula](https://github.com/mahula)**
_Tuesday Mar 07, 2023 at 19:44 GMT_

----

>Remove the `--coverage` option in all package files

Done in https://github.com/gradido/gradido/pull/2790/commits/c2de11e399aaae66824c26c9b6cee16e1a6387b8
