### ISSUE TITLE
[CLOSED] fix(admin): header and menu

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2852]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Wednesday Mar 08, 2023 at 06:54 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2793_

----

### Issues

- relates #2787 

### Todo

- [x] Logo Abstände -> Hack: auf brand `style="margin-top: -7px"`
- [x] Menu Abstände -> remove `p3` from navbar
- [x] Menu `Schöpfungen` -> remove p1

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/2793/commits_
