### ISSUE TITLE
🚀 [Feature] Order of Contribution for different tabs

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2876]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Friday Mar 10, 2023 at 12:38 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/2817_

----

## 🚀 Feature

The order we now use in the admin interface on the contribution makes the view of the "open" tab a bit strange.
I would expect to have the oldest Contributions on top and the new one at the end. 
On the other tabs it seems to have a good order but maybe we can optimize them aswell

## 🤖 Todos
- [ ] Admin Interface > Contribution: Search what order are interessant (ex. createdAt, updatedAt, confirmedAt, ...) in the 
  - [ ] open => Oldest first?
  - [ ] confirmed => Last confirmed first?
  - [ ] denied => Last denied first?
  - [ ] deleted => Last deleted first?
  - [ ] all => Last interaction first?
- [ ] Add more detailed order parameter for graphql query or mutation
