### ISSUE TITLE
🚀 [Feature] Database: Indexes for user and contribution table

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2882]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Friday Mar 10, 2023 at 13:14 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/2823_

----

## 🚀 Feature

In the admin interface we need a lot of data for the Contribution and the User tables. To optimize the query on the db we need some indexes.

## 🤖 Todos
- [ ] Indexe on all join related fields of "users" table
- [ ] Indexe on all join related fields of "contribution" table
- [ ] Other tables also
