### ISSUE TITLE
🚀 [RM-Epic] Hash-Contracting DHT-Hub

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2907]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Friday Mar 17, 2023 at 15:02 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/2848_

----

- [ ] write a legal document for contracting a foreign community's admin to follow the gradido philosphy and rules
- [ ] create a secret value for the property FEDERATION_DHT_TOPIC and keep it as a production's secret
- [ ] define how to exchange this "secret dht-topic" between Gradido-Academy and the "under contract" foreign community
