### ISSUE TITLE
🌟 [RM-EPIC] X-SendCoin API

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2914]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Friday Mar 17, 2023 at 15:11 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/2855_

----

## feature X-community-transaction with sendcoins and two-phase-commit:
  - [ ] #2947
  - [ ] in case of "local transaction" keep the logic as is
  - [ ] in case of "x-transaction" store the "sender-part" and "receiver-part" of the transaction in the table "pending_transactions" and start the "two-phase-commit" scenario
  - [ ] create a graphql-client in backend-module to invoke x-sendCoins request with the parameters 
    - [ ] "security-token" for authenticated communication only
    - [ ] "X-Transaction" type with all necessary transaction values
  - [ ] create a graphql-resolver in federation-module to process the x-sendCoins request by
    - [ ] validate the security-token
      - [ ] answer with an security error message in case of invalid security-token
    - [ ] validate the received values of the X-Transaction parameter type
      - [ ] answer with an error message in case of invalid X-Transaction values
    - [ ] in case of valid token and parameters store the "receiver-part" and "sender-part" of the X-Transaction as "pending transaction" in the table "pending_transactions" and reply with success state as an answer of the "two-phase-commit" scenario
  - [ ] finish with both commited "pending transactions" the "two-phase-commit" scenario
    - [ ] insert a "commitCoins" request in the same graphql-client of the backend-module to invoke the finishing step of the "two-phase-commit" scenario with the parameters
      - [ ] "security token" for authenticated communication only
      - [ ] "X-transaction" type with all necessary transaction values
    - [ ] insert a "commitCoins" endpoint in the same graphql resolver of the federation module
      - [ ] validate the security-token
        - [ ] answer with an security error message in case of invalid security-token
      - [ ] validate the received values of the X-Transaction parameter type
        - [ ] answer with an error message in case of invalid X-Transaction values
      - [ ] in case of valid token and parameters shift the "pending transaction" entry in the "transactions"-table and reply with success state as an answer of the "two-phase-commit" scenario
    - [ ] after successful reply invoke the shift of the lokal "pending transaction" in the "transactions"-table and trigger a state message to the user for successful "X-Transaction"
