### ISSUE TITLE
[CLOSED] fix(admin): add confirmation modal for user role change and user (un)deletion

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2939]
<a href="https://github.com/mahula"><img src="https://avatars.githubusercontent.com/u/3883288?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mahula](https://github.com/mahula)**
_Thursday Mar 23, 2023 at 19:36 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2880_

----

## 🍰 Pullrequest
In the admin interface these actions require proper confirmation modals:
- changing a user's role
- (un)deleting a user

### Issues
- fixes #2481 

### Todo
- [X] add confirmation flow to user (un)deletion actions
  - [x] remove toggle and persent the `delete` / `undelete` Button
         ![delete_user-start](https://user-images.githubusercontent.com/3883288/227336262-db1ae81f-9904-41f3-b875-bf9a19c26d1a.jpg)
         ![undelete_user-start](https://user-images.githubusercontent.com/3883288/227336267-6cc33647-d346-48d6-8ecc-e376d1781802.jpg)

  - [x] add confirmation modal for user (un)deletion actions
         ![delete_user-overlay](https://user-images.githubusercontent.com/3883288/227337461-5a6f6e74-b5c5-40cc-9ab3-4a2afb9a2d39.jpg)
        ![undelete_user-overlay](https://user-images.githubusercontent.com/3883288/227337465-ee6d2ac3-9e49-49a0-922e-d5a88b74ca73.jpg)

- [x] add confirmation flow to user role change
  - [x] disabled action button, if role is not changed
         ![change_user_role-start_without_change](https://user-images.githubusercontent.com/3883288/227344840-63c0b7d7-5dcd-4055-bfe2-338ca17b7b2f.jpg)

  - [x] enabeld action button, if role is changed
        ![change_user_role-start_with_role_changed](https://user-images.githubusercontent.com/3883288/227345183-3eabab34-a7e3-49cf-be92-67d94be5a3e6.jpg)
  - [x] add confirmation modal for user role change actions
        ![user_role_confirm_modal](https://user-images.githubusercontent.com/3883288/228295115-17cdd737-a804-443f-8794-09523426725b.jpg)

  

----

_**[mahula](https://github.com/mahula)** included the following code: https://github.com/gradido/gradido/pull/2880/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Monday Mar 27, 2023 at 21:18 GMT_

----

![image](https://user-images.githubusercontent.com/1238238/228068252-eb1c370d-7591-40ea-9e16-be37afca05d9.png)
![image](https://user-images.githubusercontent.com/1238238/228068301-cccc0420-b9d2-4d28-833b-9ab4ec60fffa.png)

Furthermore - and this is clearly not part of this PR - I think it could be wise to group this into one tab `Nutzer-Verwaltung`

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Friday Mar 31, 2023 at 08:35 GMT_

----

Found a small error in the user experience.
If a user is deleted we can still call setUserRole but the backend respond an error cause we can't access the User.
<img width="853" alt="Bildschirmfoto 2023-03-31 um 10 35 48" src="https://user-images.githubusercontent.com/33051975/229069708-0f3319d0-3695-4143-b90c-ba1da32fd57e.png">

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/mahula"><img src="https://avatars.githubusercontent.com/u/3883288?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mahula](https://github.com/mahula)**
_Friday Mar 31, 2023 at 08:36 GMT_

----

> Found a small error in the user experience. If a user is deleted we can still call setUserRole but the backend respond an error cause we can't access the User.

What about fixing this in a follow-up issue?

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Friday Mar 31, 2023 at 08:37 GMT_

----

Sure we can take the suggestions that @ulfgebhardt gave in it too!
