### ISSUE TITLE
[CLOSED] feat(frontend): add link to download QR-Code

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2948]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Friday Mar 24, 2023 at 11:24 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2889_

----

### Issues

- fixes #2825

### Todo

- [X] Add link to download QR-Code
- [x] Make unit test for add method
- [ ] Bernd needs to decide if rename 'Herunterladen' in 'Bild herunterladen', 'Bild speichern', 'QR-Code als Bild speichern'

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/2889/commits_
