### ISSUE TITLE
[CLOSED] feat(backend): mirgate transactions table for x community sendcoins

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#2976]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Tuesday Apr 04, 2023 at 21:04 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2917_

----

### Issues

- None

### Todo

- [X] migration of database
- [X] migration of entities
- [X] adapt backend logic
- [ ] adapt graphQL model  -> not part of this issue (@Mogge)

----

_**[clauspeterhuebner](https://github.com/clauspeterhuebner)** included the following code: https://github.com/gradido/gradido/pull/2917/commits_
