### ISSUE TITLE
[CLOSED] feat(federation): x com 3 introduce business communities

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#3014]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Tuesday Apr 25, 2023 at 22:34 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2955_

----

### Issues

- None

### Todo

- [x] introduce treatement of .env.devop file to handle DHT_TOPIC, DHT_SEED and KeyPair as separated secrets on production
  - [x] removed the devop solution based on disagreement in the team
- [x] on start DHT the home community entries have to be inserted/updated in database (communities + federated_communties)  

is part of issue #2956 
--------------------------------------------------------------------------
- [ ] create new graphql-handshake to get public-info (name, description, creation_date) of remote community 
**Community-UUID is NO public info and MUST be exchanged in encrypted manner per authentication process later**
  - [ ] graphql-client in backend-module for requesting public community infos
  - [ ] graphql-resolver in federation-module to process the request getPublicCommunityInfo()
- [ ] introduce backend-logic to insert a business-community entry as soon as a federated community is marked as verified_at
- [ ] update the existing business community entry with the recieved community infos

----

_**[clauspeterhuebner](https://github.com/clauspeterhuebner)** included the following code: https://github.com/gradido/gradido/pull/2955/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Wednesday May 24, 2023 at 22:01 GMT_

----

@Mogge many THX for your efforts to refactor the unit tests and to find and solve my mistake with the missing await. Great job...

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Friday May 26, 2023 at 20:02 GMT_

----

erst einmal "Danke" für deinen Approve...

Zu deinen Punkte möchte ich gerne Stellung nehmen:
* Du benennst in dem PR, der sich mit einer Tabelle beschäftigt(und deren Befüllung), die Struktur um - das hat nichts damit zu tun und gehört in einen eigenen PR - so wäre auch eine Diskussion dazu möglich, das geht jetzt leider nicht.
  - Ich habe die ursprüngliche Struktur der "Verzeichnis-basierten Versionierung", mit der dieser PR begonnen wurde, beibehalten oder besser wieder hergestellt. Das war ja genau unser auslösender Konflikt-Punkt, wo du über dein Refaktoring Einfluss auf meine Arbeit genommen hast und ich deinen Refactoring-PR nicht approved habe. Hier siehst du ganz genau welchen Einfluss dein Wirken hatte und warum deine Aussage "dein Wirken hätte in keinster Weise irgend einen Einfluss" nicht korrekt ist. Mit der hier gezeigten Lösung ist auch schon bei dieser einfachen Ausbaustufe ersichtlich (Client, Query, Model), dass eine einzige Datei "Client_1_0.ts" nicht ausreichen wird ohne diese zu überladen.

* Du machst die Ausnahme für die eslint Regel camel-case kaputt, die auf der alten Struktur aufbaut
  - Ich habe gemäß unserer Absprache bzgl CamelCase ein separates Ticket dazu erstellt und deshalb für die hier verwendeten Namenspattern keine eslint-Regel eingebaut. Da du dies ausserhalb dieses PRs in einem extra Ticket bearbeitet haben willst, daher verstehe ich dieses Argument jetzt hier nicht

* Nun sind wieder überall die eslint camel-case ausnahmen drin
  - ja das entspricht unserer gemeinsamen Vereinbarung, dass das CamelCase-Thema in einem separaten Ticket und nicht in diesem PR umgesetzt werden soll. Und die Formulierung "wieder überall" finde ich nicht passend, da diese nur darin vorkommen, wo das Namenspattern eben nicht den linting Regeln entspricht. "Überall" wäre in jeder Datei unserer Anwendung...
 
 *  du hast camel-case Ausnahmen wo sie nicht notwendig sind
    - ja sorry, eine Stelle habe ich übersehen. Denn das ist genau eine einzige Stelle und somit wäre es korrekt im Singular zu sprechen


* die meisten meiner Vorschläge zu writeHomeCommunityEntry wurden kommentarlos geschlossen
  - es gibt genau einen Kommentar von dir, zu dem ich bisher keine Anmerkung oder Antwort geschrieben habe. Und das ist der zu dem Test-Thema, wo du erwähntest, dass wenn Moritz da nichts finden würde, du dann auch nur mit unverhältnis viel Aufwand hierzu eine Lösung finden könntest. Somit verstehe ich diese Anmerkung von dir gar nicht, da dies definitiv wieder nicht korrekt ist. Kannst du mir bitte sagen wo bzw. welche deiner Review-Anmerkungen ich aus deiner Sicht gänzlich ignoriert und einfach geschlossen haben sollte? Was ist es, das dich - für mich empfunden - so masslos übertreiben lässt, dass du hier die Formulierung "die *meisten* meiner Vorschläge..." verwendest? Ich verstehe bei dieser Formulierung z.B. von 10 Anmerkungen von dir, habe ich gerade mal 2 beantwortet...
 
* Es scheint so als würdest du CommunityApi exportieren ohne es irgendwo zu importieren
  - ja die beiden Methoden wurden einmal exportiert, weil diese in meinen Lösungsansätzen der Tests direkt verwendet wurden. Dies wurde mit dem Test-Refactoring von Moritz obsolet und wurde auch von mir gemäß den Anmerkungen von Moritz wieder entfernt (siehe vorletzten Commit). Somit scheint deine Anmerkung auf einem nicht aktuellen Stand zu beruhen.


Mir scheint unsere Kommunikation auf textueller Ebene birgt sehr viel Konflikt-Potenzial. Denn genau hier kommt es aus meiner Sicht besonders auf die Wortwahl an...
