### ISSUE TITLE
feat(federation): x com 4 introduce public community info handshake

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#3016]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Thursday Apr 27, 2023 at 01:27 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2957_

----

### Issues

- None

### Todo

- [x] create new graphql-handshake to get public-info (name, description, creation_date) of remote community 
**Community-UUID is NO public info and MUST be exchanged in encrypted manner per authentication process later**
  - [x] graphql-client in backend-module for requesting public community infos
  - [x] graphql-resolver in federation-module to process the request getPublicCommunityInfo()
- [ ] update the existing business community entry with the recieved community infos

----

_**[clauspeterhuebner](https://github.com/clauspeterhuebner)** included the following code: https://github.com/gradido/gradido/pull/2957/commits_
