### ISSUE TITLE
[CLOSED] refactor(backend): replace jasonwebtoken with jose

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#3034]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Friday May 05, 2023 at 15:23 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2975_

----

## 🍰 Pullrequest

As I consider to use JWE for the authentication towards the other communities i switch the `jsonwebtoken` for `jose` which allows JWT and JWE. It is unclear up to now if JWT is sufficient or JWE is required to archieve our goals. The library looks promising tho - hence this test.

```
1. Local Community -> Request -> Other Community
2. Local Community <- Response <- Other Community
```

To proof 1 JWT is sufficient. To proof 2 JWE is required.

### Issues

- relates https://github.com/gradido/gradido/pull/2970
- relates https://github.com/gradido/gradido/pull/2965

### Todo

- [x] Does it actually work? Tests work
- [x] Does the actual frontend process work? (login etc)
- [x] research `urn` and fill in a proper value

----

_**[ulfgebhardt](https://github.com/ulfgebhardt)** included the following code: https://github.com/gradido/gradido/pull/2975/commits_
