### ISSUE TITLE
[CLOSED] fix_nginx_docker

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#312]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Tuesday Apr 27, 2021 at 20:51 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/253_

----

### The docker part

fixed frontend production docker build & refactored frontend file structure

- frontend server runs on port 3000 by default
- frontend production docker build successfully runs & builds
- frontend production docker build is no longer reachable from the outside
- moved server.js in subfolder run/

### The nginx part
nginx fix for vue interface

- localhost/vue resolves to frontend
- localhost:3000/vue resolves to frontend in development
- images are resolved properly
- remaining services are reachable as normal
- fixed image path to be relative instead of absolute
- cleaned nginx config

### Issues

- fixes #192 (fully fixed)
- fixes #131 (the path will not be configurable it has to many implications and need cross service environment variables. We should switch at a given time from old frontend to new frontend and make an adjustment. Still this issue will be closed since its no longer applicable)
- fixes #104 (finalize this issue, last remaining point: have nginx working)
- fixes #191 (no more flickering 404s should appear)
- relates #130 (fixes routing)

### Todo

- [x] Docker
- [x] Nginx
- [x] Describe and inform team about implications
- [x] Check which issues can actually be closed, which are partially fixed and which are not targeted
- [x] Describe how to test

### How to test:

1. Build docker debug images `docker-compose up --build`
2. You should now be able to reach `localhost/vue` and `localhost:3000/vue`, You should not be able to get a useful response `localhost:8080` nor `localhost:3000`
3. Test if everything is reachable as usual on `localhost/vue` and `localhost:3000/vue`:
   - login api calls work (login)
   - community api calls work (transaction list)
   - all images
   - any 404 pages?
4. Shut down the dockers `docker-compose down
5. Start and build docker environment in production mode: `docker-compose -f docker-compose.yml up --build`
6. You should now be able to reach `localhost/vue`, but you should not be able to reach `localhost:3000`, `localhost:3000/vue` nor `localhost:8080`
7. Finally test if everything is reachable as usual on `localhost/vue` and `localhost:3000/vue`:
   - login api calls work (login)
   - community api calls work (transaction list)
   - all images
   - any 404 pages?
   
### Implications (to be published on Discord)

1. You have to rebuild with `docker-compose up --build`
2. You can no longer reach the frontend with localhost:8080, you need to use either `localhost:3000/vue` or `localhost/vue`

----

_**[ulfgebhardt](https://github.com/ulfgebhardt)** included the following code: https://github.com/gradido/gradido/pull/253/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Tuesday Apr 27, 2021 at 20:56 GMT_

----

Relevant comment from Dario in #104

To make frontend reachable under / is easy, the real problem is to make community-server reachable not under /
I have already tryed everything which was suggested here:
https://stackoverflow.com/questions/2119736/cakephp-in-a-subdirectory-using-nginx-rewrite-rules

The only way I see is to load vue-frontend inside a cakephp side which I can set via routing to /
But last time I tryed to explain it to alex he didn't understand me.
In past I had put vue-client inside community-server and edited package.js and public/index.html so that on build a cakephp suitable side in template/pages/frontend.ctp was generated which was loading the vue-frontend and was accessable via /
But I don't know how to make it that Alex can work with automatic rebuild how he is used to it with that configuration.
I couldn't find a way for build vue with watch how I do it with mithril-js
(watchify ./src/app.js -t [ babelify --presets [ @babel/preset-env ] ] -o app.js -v)

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Mogge"><img src="https://avatars.githubusercontent.com/u/15882241?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mogge](https://github.com/Mogge)**
_Wednesday Apr 28, 2021 at 12:27 GMT_

----

  * localhost/vue is working
  * localhost:3000/vue is working
  * localhost:3000 is a blank page
  * localhost;8080 is not available

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Wednesday Apr 28, 2021 at 22:22 GMT_

----

I am mergin this, assume its cool with you @Mogge since the only thing we would require to test is the currently unused production build
