### ISSUE TITLE
feat(federation): authentication

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#3125]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Friday Jun 16, 2023 at 12:08 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/3066_

----

## 🍰 Pullrequest

This implements the authentication of a client as base for the authorization of a client towards the federation endpoint.
The server verifies the sent token, decrypts it and responds with his own token reencrypting the provided nonce. The client then verifies this nonce after another decryption.

### Issues

- replaces https://github.com/gradido/gradido/pull/2991
- fixes #3065 

### Todo

- [x] Get things running with typechecks, linting etc
- [x] Validate response on client
- [x] Assign authenticated middleware to getPublicKey request
- [x] Test functionality
- [ ] Write Test

----

_**[ulfgebhardt](https://github.com/ulfgebhardt)** included the following code: https://github.com/gradido/gradido/pull/3066/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Wednesday Jul 12, 2023 at 21:43 GMT_

----

> good work, but some small questions and comments
> 
> a general question about the authentification: As i interprete your code, there is no prevention about a man-in-the-middle scenario like it is solved by the OAUTH2.0 + OIDC protocol, right?

There is a timestamp - which is currently not checked.
In general this technic is most likely atackable with a replay attack - repeat the sent package and have a valid request.

I believe it is sufficient for now and analog to our `frontend <-> backend` communication. So once we decide to do the research what to use - openId/OAuth/... we can properly implement it in between frontend and backend aswell as between servers.

The point of this approach is more how to do authentication/authorization rather then actual security. I want to prove that a server found via DHT/Federation can prove its identity. This is very important since I believe if we cannot prove authentication is possible, DHT/Federation will not work, since then a culprit can just create gradido on any community. Hence its crucial we can identify a source of coins and prevent them to enter our ecosystem.

This PR has proven that this is possible, even tho not 100% foolproof on the security side of things, but that topic is for another time. The advantage with this approach is no state management. Downside is potential man-in-the-middle replay attack and CPU usage.
