### ISSUE TITLE
🌟 [EPIC] Upgrade Frontend and Admin to vue 3 and bootstrap 5

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#3130]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Sunday Jun 18, 2023 at 12:31 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/3071_

----

## 🌟 EPIC

Vue 2.7 is the current, and final minor release of Vue 2.x. Vue 2.7 receives 18 months of LTS (long-term support) starting from its release date on July 1st, 2022. During this period, Vue 2 will receive necessary bug and security fixes, but will no longer receive new features. Vue 2 will reach End of Life (EOL) on December 31st, 2023. After that date, Vue 2 will continue to be available in all existing distribution channels (CDNs and package managers), but will no longer receive updates, including security and browser compatibility fixes.

### Bekannte Einschränkungen[#](https://v3-migration.vuejs.org/migration-build.html#known-limitations)
 die verhindern können, dass Ihre App für ein Upgrade in Frage kommt:

- Abhängigkeiten, die auf internen Vue 2-APIs oder undokumentiertem Verhalten basieren. Der häufigste Fall ist die Nutzung privater Grundstücke VNodes. Wenn Ihr Projekt auf Komponentenbibliotheken wie [Vuetify](https://vuetifyjs.com/en/) , [Quasar](https://quasar.dev/) oder [ElementUI](https://element.eleme.io/#/en-US) basiert , warten Sie am besten auf deren Vue 3-kompatible Versionen.

- Unterstützung für Internet Explorer 11: [Vue 3 hat den Plan für IE11-Unterstützung offiziell eingestellt](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0038-vue3-ie11-support.md) . Wenn Sie weiterhin IE11 oder niedriger unterstützen müssen, müssen Sie bei Vue 2 bleiben.

- Serverseitiges Rendering: Der Migrations-Build kann für SSR verwendet werden, die Migration eines benutzerdefinierten SSR-Setups ist jedoch viel aufwändiger. Die allgemeine Idee ist, vue-server-rendererdurch zu ersetzen [@vue/server-renderer](https://github.com/vuejs/core/tree/master/packages/server-renderer). Vue 3 bietet keinen Bundle-Renderer mehr und es wird empfohlen, Vue 3 SSR mit [Vite](https://vitejs.dev/guide/ssr.html) zu verwenden . [Wenn Sie Nuxt.js](https://nuxtjs.org/) verwenden , ist es wahrscheinlich besser, auf Nuxt 3 zu warten.

For the upgrade of the modules frontend to vue 3 and bootstrap 5, 
we need to install the package; to remove the old package;
fix layouts of every page to the possible new structure given through vue 3 and bootstrap 5.

### Frontend:
- [ ] 🚀 [Feature] Frontend: Install vue 3 package
- [ ] 🚀 [Feature] Frontend: Install bootstrap 5 package
- [ ] 🚀 [Feature] Refactor bootstrap4 to bootstrap 5 
- [ ] 🚀 [Feature] Frontend: Refactor frontend to vue 3
- [ ] 🚀 [Feature] Frontend: Refactor frontend to bootstrap 5

### Admin:
- [ ] 🚀 [Feature] Admin: Install vue 3 package
- [ ] 🚀 [Feature] Admin: Refactor Header Component to vue 3
- [ ] 🚀 [Feature] Admin: Refactor Overview Page to vue 3
- [ ] 🚀 [Feature] Admin: Refactor User Search Page to vue 3
- [ ] 🚀 [Feature] Admin: Refactor Creation Page to vue 3
- [ ] 🚀 [Feature] Admin: Refactor Automatic Creation Page to vue 3
- [ ] 🚀 [Feature] Admin: Refactor Instances Page to vue 3
- [ ] 🚀 [Feature] Admin: Refactor Statistics Page to vue 3
