### ISSUE TITLE
[CLOSED] feat(other): proper reporting for failing end-to-end tests

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#3155]
<a href="https://github.com/mahula"><img src="https://avatars.githubusercontent.com/u/3883288?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mahula](https://github.com/mahula)**
_Thursday Jun 29, 2023 at 18:35 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/3096_

----

## 🍰 Pullrequest
Our debugging of failing end-to-end tests requires usabble reports in stead of just screenshots.
The included reporting creates expandable HTML reports leading to where a scenario fails.

A HTML report froma failing e2e test run can be found [here](https://github.com/gradido/gradido/suites/14106250692/artifacts/789227540)

### Issues
- fixes #3095 

### Todo

- [x] create HTML report
  - [x] feature overview 
          ![report_dashboard](https://github.com/gradido/gradido/assets/3883288/1a059b16-aa3a-434b-a23e-f702849cbf5d)

  - [x] expandable steps with Cypress errormessage
          ![report_scenario_01](https://github.com/gradido/gradido/assets/3883288/eb629f9d-cb68-451a-a421-1e8fff89651a)

  - [x] screenshots attached to the failing step
         ![report_scenario_02](https://github.com/gradido/gradido/assets/3883288/ed86542f-cfed-432f-ba4a-8a9f1a195441)

- [x] replace uploading screenshots by uploading the report in Github CI 

----

_**[mahula](https://github.com/mahula)** included the following code: https://github.com/gradido/gradido/pull/3096/commits_
