### ISSUE TITLE
[CLOSED] fix(admin): user role in admin interface

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#3212]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Sunday Jul 23, 2023 at 14:43 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/3153_

----

### Issues

- None

### Todo

- [X] Fix Auth Guard to check on roles
- [X] Fix user search so that the current searches work
- [x] Fix not working components

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/3153/commits_
