### ISSUE TITLE
🌟 [EPIC] Adminarea Vue 3 Migration

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#3220]
<a href="https://github.com/ogerly"><img src="https://avatars.githubusercontent.com/u/1324583?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ogerly](https://github.com/ogerly)**
_Thursday Aug 03, 2023 at 06:13 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/3161_

----

## 🌟 EPIC

Der Adminbereich wird von Vue 2 zu Vue 3 

# Migration der Gradido Adminarea Vue 2-Anwendung zu Vue 3

## Schritt 1: Vorbereitung mit Vite
- **Backup**: Erstelle eine vollständige Sicherung deiner Vue 2-Anwendung.
- **CLI**: Stelle deine CLI Vue 2 Anwendung auf Vite um  [Vite](https://vitejs.dev/)

- [ ] https://github.com/gradido/gradido/issues/3167

Durch die vorherige umstellung von CLI auf Vite lässt sich die Migration reibungsloser vollziehen.
- [ ] https://github.com/gradido/gradido/issues/3163

#### Vite macht im Wesentlichen zwei Dinge:
 

> - stellt einen Entwicklungsserver mit HMR (Hot Module Reloading) bereit
> - baut Projekte für die Produktion

 
#### Vorteile durch die Migration zu Vite
 

> - Vite wurde entwickelt, um eine schnelle Feedbackschleife in der Entwicklung zu erreichen, 
> - Die Startzeit des Entwicklungsservers ist unvergleichlich kurz
> - Codeänderungen werden sofort im Browser angezeigt. Es werden nur die geänderten Komponenten neu geladen. 
> - Es ist nicht erforderlich, die gesamte Anwendung neu zu erstellen.
> - Vite vereinfacht den Entwicklungsaufbau erheblich. Sie können Webpack, Babel und Vue CLI mit ihren Plugins, 
> Loadern und komplexen Konfigurationen wegwerfen.
> - Kleinere Produktionsaufbauten dank Rollup, das Vite unter der Haube verwendet.
> - Schnellere Bereitstellungen aufgrund kürzerer Build-Zeit.

 
 

## Schritt 2: Aktualisierung der Abhängigkeiten
- [ ] Überprüfe und aktualisiere die Paketabhängigkeiten in `package.json` auf die neuesten Vue 3-Versionen. https://github.com/gradido/gradido/issues/3162

## Schritt 3: Vue 2.x to 3.x Migrationstool
- Führe das offizielle Vue 2.x to 3.x Migrationstool aus, um automatische Änderungen zu übernehmen.
-  [ ] https://github.com/gradido/gradido/issues/3164

## Schritt 4: Umstellung der Bootstrap Komponenten auf Version 5
- Aktualisiere Bootstrap auf die Vue 3-kompatible Version.
- [x] https://github.com/gradido/gradido/issues/3165

## Schritt 4.1: Umstellung der Apollo Client Komponenten auf Version 3
- Aktualisiere  den Apollo Client  auf die Vue 3-kompatible Version.
- [ ] https://github.com/gradido/gradido/issues/3166

### Global API[#](https://v3-migration.vuejs.org/breaking-changes/#global-api)
- [ ] [Global Vue API is changed to use an application instance](https://v3-migration.vuejs.org/breaking-changes/global-api)
- [ ] [Global and internal APIs have been restructured to be tree-shakable](https://v3-migration.vuejs.org/breaking-changes/global-api-treeshaking)

### Template Directives[#](https://v3-migration.vuejs.org/breaking-changes/#template-directives)
- [ ] [v-model usage on components has been reworked, replacing v-bind.sync](https://v3-migration.vuejs.org/breaking-changes/v-model)
- [ ] [key usage on <template v-for> and non-v-for nodes has changed](https://v3-migration.vuejs.org/breaking-changes/key-attribute)
- [ ] [v-if and v-for precedence when used on the same element has changed](https://v3-migration.vuejs.org/breaking-changes/v-if-v-for)
- [ ] [v-bind="object" is now order-sensitive](https://v3-migration.vuejs.org/breaking-changes/v-bind)
- [ ] [v-on:event.native modifier has been removed](https://v3-migration.vuejs.org/breaking-changes/v-on-native-modifier-removed)

### Components[#](https://v3-migration.vuejs.org/breaking-changes/#components)
- [ ] [Functional components can only be created using a plain function](https://v3-migration.vuejs.org/breaking-changes/functional-components)
- [ ] [functional attribute on single-file component (SFC) <template> and functional component option are deprecated](https://v3-migration.vuejs.org/breaking-changes/functional-components)
- [ ] [Async components now require defineAsyncComponent method to be created](https://v3-migration.vuejs.org/breaking-changes/async-components)
- [ ] [Component events should now be declared with the emits option](https://v3-migration.vuejs.org/breaking-changes/emits-option)

### Render Function[#](https://v3-migration.vuejs.org/breaking-changes/#render-function)
- [ ] [Render function API changed](https://v3-migration.vuejs.org/breaking-changes/render-function-api)
- [ ] [$scopedSlots property is removed and all slots are exposed via $slots as functions](https://v3-migration.vuejs.org/breaking-changes/slots-unification)
- [ ] [$listeners has been removed / merged into $attrs](https://v3-migration.vuejs.org/breaking-changes/listeners-removed)
- [ ] [$attrs now includes class and style attributes](https://v3-migration.vuejs.org/breaking-changes/attrs-includes-class-style)

### Custom Elements[#](https://v3-migration.vuejs.org/breaking-changes/#custom-elements)
- [ ] [Custom element checks are now performed during template compilation](https://v3-migration.vuejs.org/breaking-changes/custom-elements-interop)
- [ ] [Special is attribute usage is restricted to the reserved <component> tag only](https://v3-migration.vuejs.org/breaking-changes/custom-elements-interop#customized-built-in-elements)

### Other Minor Changes[#](https://v3-migration.vuejs.org/breaking-changes/#other-minor-changes)
- [ ] The destroyed lifecycle option has been renamed to unmounted
- [ ] The beforeDestroy lifecycle option has been renamed to beforeUnmount
- [ ] [Props default factory function no longer has access to this context](https://v3-migration.vuejs.org/breaking-changes/props-default-this)
- [ ] [Custom directive API changed to align with component lifecycle and binding.expression removed](https://v3-migration.vuejs.org/breaking-changes/custom-directives)
- [ ] [The data option should always be declared as a function](https://v3-migration.vuejs.org/breaking-changes/data-option)
- [ ] [The data option from mixins is now merged shallowly](https://v3-migration.vuejs.org/breaking-changes/data-option#mixin-merge-behavior-change)
- [ ] [Attributes coercion strategy changed](https://v3-migration.vuejs.org/breaking-changes/attribute-coercion)
- [ ] [Some transition classes got a rename](https://v3-migration.vuejs.org/breaking-changes/transition)
- [ ] [<TransitionGroup> now renders no wrapper element by default](https://v3-migration.vuejs.org/breaking-changes/transition-group)
- [ ] [When watching an array, the callback will only trigger when the array is replaced. If you need to trigger on mutation, the deep option must be specified.](https://v3-migration.vuejs.org/breaking-changes/watch)
- [ ] <template> tags with no special directives (v-if/else-if/else, v-for, or v-slot) are now treated as plain elements and will result in a native <template> element instead of rendering its inner content.
- [ ] [Mounted application does not replace the element it's mounted to](https://v3-migration.vuejs.org/breaking-changes/mount-changes)
- [ ] [Lifecycle hook: events prefix changed to vnode-](https://v3-migration.vuejs.org/breaking-changes/vnode-lifecycle-events)

### Removed APIs[#](https://v3-migration.vuejs.org/breaking-changes/#removed-apis)
- [ ] [keyCode support as v-on modifiers](https://v3-migration.vuejs.org/breaking-changes/keycode-modifiers)
- [ ] [$on, $off and $once instance methods](https://v3-migration.vuejs.org/breaking-changes/events-api)
- [ ] [Filters](https://v3-migration.vuejs.org/breaking-changes/filters)
- [ ] [Inline templates attributes](https://v3-migration.vuejs.org/breaking-changes/inline-template-attribute)
- [ ] [$children instance property](https://v3-migration.vuejs.org/breaking-changes/children)
- [ ] [propsData option](https://v3-migration.vuejs.org/breaking-changes/props-data)
- [ ] $destroy instance method. Users should no longer manually manage the lifecycle of individual Vue components.
- [ ] Global functions set and delete, and the instance methods $set and $delete. They are no longer required with proxy-based change detection.

Bitte achte darauf das alle punkte sauber abgehakt werden können! Bitte prüfe noch mal anhand [dieses Links](https://v3-migration.vuejs.org/breaking-changes/):  

## Schritt 6: Vue Router
- Aktualisiere Vue Router auf die Vue 3-kompatible Version.
- Passe Router-Code an API-Änderungen an, falls erforderlich.

## Schritt 7: Vuex
- Aktualisiere Vuex auf die Vue 3-kompatible Version.
- Ändere die Komponenten-Verbindung zu Vuex, z. B. durch `mapState`, `mapGetters`.
- Ziehe wenn nötig, Schritt 10: Store-Optimierung, vor. 

## Schritt 8: Testen
- Führe umfangreiche Tests durch, um die Funktionalität und Integrationen zu überprüfen.

## Schritt 9: Linting und Code-Qualität
- Führe einen Linting-Durchlauf durch, um den Code den aktuellen Standards anzupassen.

## Schritt 10: Store-Optimierung
- Überprüfe die Anwendung auf mögliche Store-Verbesserungen durch [Pinia](https://pinia.vuejs.org/)  für Vue 3.

> Pinia ist eine State Management Library für Vue.js. Es bietet eine einfachere und leichter zu verstehende API als Vuex, die Standard-State-Management-Lösung für Vue.js. Hier sind einige der Hauptmerkmale von Pinia:
> 
> Bessere Typsicherheit: Pinia hat eine ausgezeichnete Unterstützung für TypeScript, was es zu einer guten Wahl für Projekte macht, die starke Typsicherheit erfordern.
> 
> Einfachere API: Pinia hat eine einfachere und intuitivere API im Vergleich zu Vuex. Dies macht es einfacher zu lernen und zu verwenden, besonders für Anfänger.
> 
> Leichtgewichtig: Pinia ist kleiner und effizienter als Vuex, was zu schnelleren Ladezeiten und besserer Leistung führt.
> 
> DevTools-Integration: Pinia hat eine eingebaute Integration mit Vue DevTools, was das Debuggen von Anwendungen erleichtert.
> 
> Pinia ist kompatibel mit Vue 2 und Vue 3, so dass es in einer Vielzahl von Projekten eingesetzt werden kann.

## Schritt 11: Performance-Optimierung
- Überprüfe die Anwendung auf mögliche Performance-Verbesserungen durch Vue 3.

## Schritt 12: Anwendungsstart und Überwachung
- Starte die migrierte Anwendung und überwache die Konsolenausgaben und das Verhalten.

## Schritt 13: Dokumentation
- Aktualisiere die Dokumentation, um alle Änderungen und Besonderheiten in Vue 3 widerzuspiegeln.

Beachte, dass die genaue Migrationsstrategie von der Komplexität deiner Anwendung und den verwendeten Bibliotheken abhängen kann. Lese die Vue 3-Migrationsanleitung und die Dokumentation der genutzten Bibliotheken sorgfältig durch, um potenzielle Herausforderungen zu identifizieren. Teste regelmäßig, um Probleme frühzeitig zu erkennen und zu beheben.

[Vue 3 Migration Guide](https://v3-migration.vuejs.org/migration-build.html)
