### ISSUE TITLE
[CLOSED] 🌟 [EPIC] 1.0.0 New Vue Interface

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#58]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Thursday Mar 11, 2021 at 03:45 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/40_

----

## 🌟 EPIC

Gradido is now live in the so called `Stage1`.
- [x] User data is ported
- [x] We have a stable deployment
- [x] Vue Interface had its first tests and is considered beta/usable
- [x] We go open source as far as we can
- [x] We do first tests for decentralization
