### ISSUE TITLE
[CLOSED] Backend Setup

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#643]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Wednesday Jun 23, 2021 at 21:20 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/584_

----

## 🍰 Pullrequest

Backend Setup.

This PR is the first step for a nodejs based backend server. This PR can be merged as soon as the communication between client and server is completely covered by the new backend. Furthermore authentication via JWT would be a good feature to start with

#### TechStack
- [x] typescript
- [x] express
- [x] express-graphql
- [x] eslint
- [x] prettier
- [x] ~~jest~~
- [x] publish workflow
- [x] lint workflow
- [x] ~~test workflow~~
- [x] docker

### Issues

- fixes #692 
- relates #13
- relates #17 
- relates #477 

### Todo

- [x] ~~Implement jest~~
- [x] Make Issue for jest and test workflow
- [x] Implement docker
- [x] Implement docker-compose setup
- [x] Implement workflows
- [x] ~~Implement typeorm connection~~
- [ ] Make Issue for typeorm implementation
- [x] Implement proper graphql schema
- [x] Issue: API Versioning?
- [x] Config (enable graphiql, debug, which api version is supported, port)
- [x] Implement API connection to Login Server
- [x] Make Issue JWT based on old session
- [x] Remove Book examples

----

_**[ulfgebhardt](https://github.com/ulfgebhardt)** included the following code: https://github.com/gradido/gradido/pull/584/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/einhornimmond"><img src="https://avatars.githubusercontent.com/u/67117805?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [einhornimmond](https://github.com/einhornimmond)**
_Thursday Jun 24, 2021 at 16:30 GMT_

----

Try Login User, but I get this error:
```
Cannot find module 'class-validator'\nRequire stack:\n- F:\\Gradido\\gradido_apollo\\backend\\node_modules\\type-graphql\\dist\\resolvers\\validate-arg.js\n- F:\\Gradido\\gradido_apollo\\backend\\node_modules\\type-graphql\\dist\\resolvers\\helpers.js\n- F:\\Gradido\\gradido_apollo\\backend\\node_modules\\type-graphql\\dist\\resolvers\\create.js\n- F:\\Gradido\\gradido_apollo\\backend\\node_modules\\type-graphql\\dist\\schema\\schema-generator.js\n- F:\\Gradido\\gradido_apollo\\backend\\node_modules\\type-graphql\\dist\\utils\\buildSchema.js\n- F:\\Gradido\\gradido_apollo\\backend\\node_modules\\type-graphql\\dist\\utils\\index.js\n- F:\\Gradido\\gradido_apollo\\backend\\node_modules\\type-graphql\\dist\\index.js\n- F:\\Gradido\\gradido_apollo\\backend\\src\\index.ts
```

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Monday Aug 02, 2021 at 11:00 GMT_

----

Hi @ulfgebhardt, @Mogge, @einhornimmond, 

like we discussed in the last meetings I worked on this issue so we can tunnel the Login & Community Server calls over the Apollo Server.
What @ulfgebhardt and @Mogge prepared was clear so I could understand the base structure and continue to implement the different calls.

Now I am a bit concerned about the datas we want to send.
For the moment we use the two Methods apiPost and apiGet that were writen for the frontend, the methods do interpret the response of the servers.
 
The different szenaries for apiPost are:
Error Cases:
- The state is different from 200 the call send an ErrorObject that is given to the response
- The data.state is warning send an ErrorObject that is also returned in the JSON
Response: error is the catched JavaScript object
```
{
success: false,
result: error
}
```

Success:
Response: result is the axio result object
```
{
success: false,
result: result
}
```

So my question do we need the whole axio response object and the whole error object when we go out of the apiPost Method? Does the frontend need this objects to interpret things?
Or can I withdraw the two objects and use a simplified result like:
ErrorJSON
```
{
  success: false,
  result: error.message
}
```
SuccessJSON
```
{
  success: true,
  result: result.data
}
```

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Monday Aug 02, 2021 at 11:05 GMT_

----

No the whole object is not needed - feel free to structure the graphql response as you wish. Limit the information you send out to what the client needs.
In this case I would always throw an error whenever `success != true` and let graphql handle the error. The thrown error can contain data which could be used by the client if needed.

This way we have an uniform result:
1. Success case - the structured data
2. Failure case - throw an error and use graphql error propagation

Error

`throw new Error(error.message)`

SuccessJSON

```
{
  success: true, //maybe omit this aswell?
  result: result.data
}
```

On the client the success is then no longer determined by a field in the result object but by the graphql interface - call successful or not - if not with what error

Sounds good?

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Monday Aug 02, 2021 at 14:15 GMT_

----

OK sounds great. So something like the following code would do it:
```
@Query(() => LoginResponse)
async login(@Args() { email, password }: UnsecureLoginArgs): Promise<LoginResponse> {
    email = email.trim().toLowerCase()
    const result = await apiPost(CONFIG.LOGIN_API_URL + 'unsecureLogin', { email, password })

    if (!result.success) {
      throw new Error(result.data)
    }
    
    return new LoginResponse(result.data)
  }
  ```
