### ISSUE TITLE
[CLOSED] Integration of the KlicktippAPI to the User management

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#812]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elweyn](https://github.com/Elweyn)**
_Friday Aug 20, 2021 at 09:21 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/753_

----

## 🍰 Pullrequest
Gradido wants to registrate the new users to the Klicktipp newsletters and give the user a overview of the newsletter in which he is registrated.

### Issues
- fixes: #729
- fixes: #185 
- fixes: #605 

### Todo
- [x] Find the authentication 
- [x] Test if the code works
- [ ] Implement the UserProfile_Newletter module that can manage the newsletter in which a user is registrated
- [ ] Frontend implementation Register
- [ ] Frontend implementation User Profile
- [ ] Apollo implementation Middleware that intercepts the call back after checkEmail from the login_server
- [ ] Login_server change the response url so that Apollo can intercept the optin callback 

----

_**[Elweyn](https://github.com/Elweyn)** included the following code: https://github.com/gradido/gradido/pull/753/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Friday Aug 20, 2021 at 10:43 GMT_

----

@Mogge @Elweyn Wir haben flaky tests - ohne Änderung schlagen die Frontend tests fehl 
![image](https://user-images.githubusercontent.com/1238238/130221921-eee88a73-50be-46dc-8190-47b89f7f365a.png)
