### ISSUE TITLE
[CLOSED] database_migrations

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#829]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Sunday Aug 22, 2021 at 11:35 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/770_

----

## 🍰 Pullrequest

Replace skeema and have a full migration service with up and down capabilities for complex migration tasks.

### Issues

- fixes #315 
- fixes #94 
- fixes #704 

### Todo

- [x] Basic Setup & Library choices
- [x] Complete setup to have working migration functionality
- [x] Linting
- [x] Import all Database definitions from skeema
- [x] Import all Database Values from skeema
- [x] Docker integration
- [x] Backend integration (restart till correct database version is present)
- [x] Workflow Integration

**This PR affects the database. Take care, make a backup and read carefully. `docker-compose up --build` will render some test inaccessible.**

**This PR requires a docker rebuild `docker-compose up --build`, since skeema & mariadb are affected and those are not responsive to changes in the codebase**

### How 2 Test

To test this you can simply run docker `docker-compose up --build` on an empty database. This will create a database `gradido_community` with a few tables including `migrations` which will include `fileName` as column and one row including `0001-init_db` as fileName.

If you already have a database consider to make a backup and check the `gradido_community` database for a `migrations` table which includes a field `db_version` (to bring up the database without starting the migrations run `docker-compose up --build mariadb`). Once you run `docker-compose up --build` this should change to a new `migrations` table with the `fileName` column and one row including `0001-init_db` as fileName. This operation should not affect the data in your database except for the `migrations` table

For further testing you can run `docker-compose run -T database yarn reset` which will run a complete `down`iteration of the database and a complete `up` iteration. Be aware that this will delete the whole content of your database.

----

_**[ulfgebhardt](https://github.com/ulfgebhardt)** included the following code: https://github.com/gradido/gradido/pull/770/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Monday Aug 23, 2021 at 15:04 GMT_

----

> Cannot wait to have seeding!

We only have reset with this. Factories can live in this subproject tho. @Mogge
