### ISSUE TITLE
[CLOSED] 🚀 [Feature] registration process on the community instance

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#863]
<a href="https://github.com/clauspeterhuebner"><img src="https://avatars.githubusercontent.com/u/86960882?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clauspeterhuebner](https://github.com/clauspeterhuebner)**
_Tuesday Sep 14, 2021 at 00:03 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/804_

----

## 🚀 Feature

1. equates to the existing registration page of the gradido application
2. the process steps equates to the existing steps of the current registration process
3. at the end of the registration process the registration on elopage will be triggered including the PID parameter
4. take in acount the result of the issue #187 for triggring the elopage registration process

## TODOs
- [x] When User login gets a flag if his email is registered on the gdt server #949 
- [x] If yes button "Member Area" sends us to the Elopage Account 
- [x] if not button "..." has a visual queu (Red exclamation button) and sends us to the Elopage Registration "https://elopage.com/s/gradido/basic-de/payment?locale=de&prid=111&pid=&firstName=&lastName=&email="

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Wednesday Sep 15, 2021 at 13:27 GMT_

----

Point 3 will not be possible since Elopage does not allow user registration via api according to our research @clauspeterhuebner

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Monday Sep 27, 2021 at 10:44 GMT_

----

@ulfgebhardt, @clauspeterhuebner,
After talkung to the elopage support we need a deeplink to the registration of Elopage we can not use an API.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Tuesday Oct 12, 2021 at 09:34 GMT_

----

Tasks should be the following:
- [ ] When User login gets a flag if his email is registered on the gdt server
- [ ] If yes button "Member Area" sends us to the Elopage Account
- [ ] if not button "..." has a visual queu (Red exclamation button) and sends us to the Elopage Registration "https://elopage.com/s/gradido/basic-de/payment?locale=de&prid=111&pid=&firstName=&lastName=&email="
- [ ]
