### ISSUE TITLE
[CLOSED] decay calculation is calculated 

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#874]
<a href="https://github.com/ogerly"><img src="https://avatars.githubusercontent.com/u/1324583?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ogerly](https://github.com/ogerly)**
_Thursday Sep 16, 2021 at 13:57 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/815_

----

## 🍰 Pullrequest
decay calculation is calculated and displayed at the transaction in a more user-friendly way

![FireShot Capture 502 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/133625312-03d616df-658f-4938-acc2-002e9d557d8a.png)

### Issues
- fixes #636
 
### Todo

wir haben im momentanen zustand keine möglichkeit bei einer transaktion auflistung  dem user vor seiner transaktion den absoluten stand seines GDD betrages (absoluter kontostand)  >> sowie nach der transaktion + vergänglichkeit den neuen aktuellen betrag seines kontostandes anzeigen. weil diese daten nicht zur verfügung stehen. 

ich würde den vorschlag machen darüber zu diskutieren ob es gut wäre eben diese aktuellen kontostände vor und nach einer beliebigen transaktion. in dem jetzigen zustand ist das absolut nicht userfreundlich .. weil es nicht darstellbar ist .. 

ausser du kannst es mir  in der "export const transactionsQuery = gql`
" irgendwie mitliefern ..  was aber vorrausichtich sehr rechenintensiv ist ..  

----

_**[ogerly](https://github.com/ogerly)** included the following code: https://github.com/gradido/gradido/pull/815/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Monday Sep 20, 2021 at 18:41 GMT_

----

@ogerly Ich verstehe die Einschränkungen, die mit der fehlenden Balance einhergehen (siehe #869), aber im aktuellen Zustand würde ich davon absehen es zu mergen, da nun beschrieben wird, dass `Gesendet 209,64` und das halte ich für inkorrekt.
Was sagst du?

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Tuesday Sep 21, 2021 at 07:11 GMT_

----

@ulfgebhardt, @clauspeterhuebner,
@ogerly and I have looked at this PR and we need to clarify if the new textes in the collapse block are meaningful enough:
- For Send: 
Are the textes: Betrag, Vergänglichkeit, Gesendet OK? Or should we change the 'Gesendet' to something like 'Gesammt Betrag (Betrag + Vergänglichkeit)'?
- For Receive:
Are the textes: Betrag, Vergänglichkeit, Empfangen OK? Or should we change the 'Empfangen' to something like 'Gesammt Betrag (Betrag - Vergänglichkeit)'?

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Tuesday Sep 21, 2021 at 12:36 GMT_

----

![image](https://user-images.githubusercontent.com/1238238/134169972-24faa292-3f34-4a37-9995-cb5a67537a11.png)

- [ ] Rechnung Darstellung(+,-, Strich)
- [ ] Kontostand gesamt (bedarf darios hillfe)
- [ ] Abstände zwischen den einzelnen Teilen (vll <hr>)

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ogerly"><img src="https://avatars.githubusercontent.com/u/1324583?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ogerly](https://github.com/ogerly)**
_Thursday Sep 23, 2021 at 06:56 GMT_

----

![FireShot Capture 542 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/134465869-00ee04a3-5eed-4e18-a774-42a8df9a7490.png)

![FireShot Capture 543 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/134465877-f6be68ae-56cd-4246-a749-c1475d94f0e7.png)

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Thursday Sep 23, 2021 at 18:37 GMT_

----

@ogerly 
Magst du bitte auch hier rows und cols verwenden? Warum 47 zu 53% width?
Ich würde nun gerne noch den Decay Bereich vom Kontostand Berechnungsbereich trennen, wenn das geht - ggf mit einer weiteren Überschrift.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ogerly"><img src="https://avatars.githubusercontent.com/u/1324583?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ogerly](https://github.com/ogerly)**
_Friday Sep 24, 2021 at 10:29 GMT_

----

![FireShot Capture 553 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/134660334-67bde1d4-091a-48e0-91e3-76572e3e0d83.png)

![FireShot Capture 554 - Gradido Account - localhost](https://user-images.githubusercontent.com/1324583/134660348-2da91b59-0a14-47e9-a1d9-88416c90dbd4.png)
