### ISSUE TITLE
[CLOSED] Implement getBalance in Apollo

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#890]
<a href="https://github.com/einhornimmond"><img src="https://avatars.githubusercontent.com/u/67117805?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [einhornimmond](https://github.com/einhornimmond)**
_Friday Sep 17, 2021 at 19:26 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/831_

----

## 🍰 Pullrequest
- use typeorm for direct access to saved balance in db
- create typeorm models
- add decay function to apollo
- 
### Issues
- fixes #820

### Todo
- [x] Create user typeorm entity
- [x] Create balance typeorm entity
- [x] Add decay calculation function (maybe in util folder?)
- [x] Update getBalance Resolver code
- [x] merge #881

### Why I need the state_user table for that?
state_balances use the state_user_id as foreign key, so first I must get the user public key from login-server, read from state_users with that and than use id for reading the correct balance entry from db. 

----

_**[einhornimmond](https://github.com/einhornimmond)** included the following code: https://github.com/gradido/gradido/pull/831/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Saturday Sep 18, 2021 at 18:51 GMT_

----

@einhornimmond Wollen wir das nicht in Zukunft so machen? https://stackoverflow.com/questions/56311203/can-i-map-entity-field-names-to-alias-column-names-in-typeorm

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/einhornimmond"><img src="https://avatars.githubusercontent.com/u/67117805?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [einhornimmond](https://github.com/einhornimmond)**
_Saturday Sep 18, 2021 at 19:43 GMT_

----

Yes, great. I have searched for something like that but not found.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/einhornimmond"><img src="https://avatars.githubusercontent.com/u/67117805?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [einhornimmond](https://github.com/einhornimmond)**
_Tuesday Sep 21, 2021 at 09:37 GMT_

----

> Great - tho the balance call is way less code then expected. This is a great step!

Yes but this has to do with ignoring a big peace of code entirely. 
I don't use the auto-error-correction code from community-server. It seems that the decay calculation is now stable so we maybe don't need it any longer. But it could lead to errors in future.
