### ISSUE TITLE
[CLOSED] 🔧 [Refactor] Implement Login Call createUser on Apollo 

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#894]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Saturday Sep 18, 2021 at 11:04 GMT_
_Originally opened as https://github.com/gradido/gradido/issues/835_

----

## 🔧 Refactor ticket

Implement Login Call createUser on Apollo 
## ToDos:
- [ ] Query user with email: if exists throw Error('user already exists')?
- [ ] Check Password validity? 
- [ ] Create an DbUser with the provided values in it
- [ ] Save DbUser, if error => Throw Error
- [ ] See if we need the Pubkey & Privkey
- [ ] Case yes: Implement it
- [ ] Case no: remove it
- [ ] Implement EmailOptIn logic

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Saturday Oct 23, 2021 at 08:44 GMT_

----

I lost everything I just analysed... So I will rewritte it!

Logic:
```
- Takes the following parameters out of the request: email, first_name, last_name, emailType, group_id, username, description, language, password, login_after_register and publisher_id
- Creates an Empty User Model Object and a User Db Object
- Tries to load a User from the create Model with this email => if exists send error result (Already exists)
- Check Password => If not valid send error
- Creates User Model and User Db Model with the following parameters: email, first_name, last_name, group_id
- check username size <= 3 and username already used => Send error
- if description size > 3 set description in model
- language has a code behind => set languageKey in model
- set publisherId in model
- Has User been stored in DB => No? Send error
- Password size > 0 => set userModel in session
- generateKeys.... Creates a passphrase and stores it in user_backup... For what is that used for????
- updatePubkeyAndPrivkey or updatePublickey from user Model
- if result_save_key is false => send error 
- Create a new EmailOptIn in DB
- if Not stored => Send Email with error & return error state
- EmailManager add prepared Email
- prepare successResult
- add User Model to successResult
- add sessionId to successResult
```

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Elweyn"><img src="https://avatars.githubusercontent.com/u/33051975?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Elweyn](https://github.com/Elweyn)**
_Saturday Oct 23, 2021 at 09:25 GMT_

----

So I would do this logic in the Apollo backend:
ToDos:
- [ ] Query user with email: if exists throw Error('user already exists')?
- [ ] Check Password validity? 
- [ ] Create an DbUser with the provided values in it
- [ ] Save DbUser, if error => Throw Error
- [ ] See if we need the Pubkey & Privkey
- [ ] Case yes: Implement it
- [ ] Case no: remove it
- [ ] Implement EmailOptIn logic
