### ISSUE TITLE
[CLOSED] Apollo list transactions

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#952]
<a href="https://github.com/einhornimmond"><img src="https://avatars.githubusercontent.com/u/67117805?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [einhornimmond](https://github.com/einhornimmond)**
_Friday Sep 24, 2021 at 09:05 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/893_

----

## 🍰 Pullrequest
Implement listTransactions call from Community Server into Apollo

### Issues
- fixes #822 

### Todo 
- [x] load gdt sum and gdd balance with decay
- [x] add UserTransaction Model for table state_user_transactions
- [x] implement paging 
- [x] add Transactions Model for table transactions
- [x] add TransactionSendCoin Model for table transaction_send_coins
- [x] add TransactionCreation Model for table transaction_creations
- [x] implement calculating decay transactions and add them 

----

_**[einhornimmond](https://github.com/einhornimmond)** included the following code: https://github.com/gradido/gradido/pull/893/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Tuesday Sep 28, 2021 at 17:11 GMT_

----

This looks very good. What is missing?

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/einhornimmond"><img src="https://avatars.githubusercontent.com/u/67117805?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [einhornimmond](https://github.com/einhornimmond)**
_Wednesday Sep 29, 2021 at 08:33 GMT_

----

Decay don't work properly
